### PR TITLE
Pr/1113 after merging develop

### PR DESCRIPTION
**Pull request by aleks-f**

### CODE REVIEW

**Comment by aleks-f** [comment]
@zosrothko : I merged dev and fixed a conflict. travis is timing out and appveyor fails on pocomsg compilation, can you check what's going on?

**Comment by zosrothko** [comment]
Both AppVeyor fail du to a missing source: CppUnit/TestCaller.h
C:\projects\poco\Data\ODBC\testsuite\src\ODBCSybaseTest.cpp(27) : fatal error C1083: Cannot open include file: 'CppUnit/TestCaller.h': No such file or directory
NMAKE : fatal error
 U1077: 'C:\PROGRA~2\MICROS~3.0\VC\bin\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error
 U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error
 U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.

The pocomsg error is already managed using PS exception handling and should not cause the job to fail.

**Comment by zosrothko** [comment]
Travis is down since this morning. I notified the Travis support but nothing happened yet.

**Comment by aleks-f** [comment]
@zosrothko : that is strange, I have no problem building
```
1>------ Rebuild All started: Project: CppUnit, Configuration: debug_shared Win32 ------
1>  TextTestResult.cpp
1>  TestSuite.cpp
1>  TestRunner.cpp
1>  TestResult.cpp
1>  TestFailure.cpp
1>  TestDecorator.cpp
1>  TestCase.cpp
1>  CppUnitException.cpp
1>  Generating Code...
1>     Creating library ..\lib\PocoCppUnitd.lib and object ..\lib\PocoCppUnitd.exp
1>  CppUnit_vs120.vcxproj -> C:\poco\CppUnit\..\bin\PocoCppUnitd.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

**Comment by aleks-f** [comment]
ah, it's sybase - I'll take a look at that, it's because Sybase nad PostgreSQL were not in your branch when you did the modification

**Comment by aleks-f** [comment]
ok, I'm not sure why travis is failing - I think this is good to merge. @zosrothko

**Pull request merged**
