### PR TITLE
Let the build system honor flags

### PR DESCRIPTION
**Pull request by jspricke**
Try to append flags where possible. Also remove the -Ox flags set by upstream

### CODE REVIEW

**Comment by jspricke** [comment]
This has been part of the Debian patchset for quite some time and even seems to be proposed on the old sourceforge site.

**Comment by obiltschnig** [comment]
Removing the -O2 flags from the default Linux and FreeBSD build configurations is not a good idea, as people building POCO from source will end up with unoptimized release builds by default.

**Comment by obiltschnig** [comment]
Maybe having a separate build configuration for these build systems is a better idea?

**Comment by jspricke** [comment]
Good point cmake has type None for that. Maybe I will simply switch the Debian build to it.

**Comment by jspricke** [comment]
Would the rest of the patch be accaptable? Should I update it?

**Pull request closed without merging**
