### PR TITLE
Add android build on travis

### PR DESCRIPTION
**Pull request by Bjoe**
Add android build on travis.

### CODE REVIEW

**Comment by Bjoe** [comment]
@obiltschnig This is only to get faster an result. After android build is working I will comment all in and squash all commits.

**Comment by obiltschnig** [comment]
Wouldn't it be faster to set up Travis for your fork?

**Comment by obiltschnig** [comment]
I guess we don't need to merge this for now, as Travis builds your PR anyway ;-)

**Comment by Bjoe** [comment]
> Wouldn't it be faster to set up Travis for your fork?

Would be better, but travis is not building on my fork... but maybe I should create a pull request in my own fork?

**Comment by Bjoe** [comment]
> ... but maybe I should create a pull request in my own fork?

No sorry. Travis is not building in my fork. Only when I create a pull request to poco, travis builds my branch.

**Comment by zosrothko** [comment]
@Bjoe "Travis is not building in my fork.".. Yes Travis is building your fork, but you have before to add your github repository to the travis workflow. Go on Travis and open you account. Then add your poco's fork

**Comment by Bjoe** [comment]
@obiltschnig Ok I cleanup/enable all builds in travis.yml and squashed my commits. 
Unfortunately the android emulator is not yet running :-( I will figured out.

At the moment the android build will fail because we have two issues in android. These are fixed in #1983 and #1975

**Comment by Bjoe** [comment]
Ok, done. Now it is ready to be merged, after review is done :-)

I added two android builds. I think POCO should support as minimum API level 19 and as newest 24. These are the most distributed android platform versions. See [Platform Versions](https://developer.android.com/about/dashboards/index.html)

There are still some open issues:
- Failing tests: Failing tests are fixed in pull request #2035
- Build for android API level 19 is crashing in android emulator for API level 19 with following output:
> Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 1690 (Foundation-test)
> backtrace:
>     #00  pc 00000000  <unknown>
>     #01  pc 00049d63  /data/local/tmp/lib/libCppUnitd.so (std::__ndk1::__stdinbuf<char>::imbue(std::__ndk1::locale const&)+26)
>     #02  pc 00049a71  /data/local/tmp/lib/libCppUnitd.so (std::__ndk1::__stdinbuf<char>::__stdinbuf(__sFILE*, mbstate_t*)+72)

I think the problem has something to do with the standard C++ library. I will figure out what is the problem. For the first time, I decided to use the android API level 24 at runtime.

- Unfortunately the android NDK didn't provide any OpenSSL version, so all crypto tests are not running. But I think POCO should have this.

For the develop branch, should I create also a pull request?

**Comment by Bjoe** [comment]
Ok here some few points to discuss:

- added a ENABLE_LONG_RUNNING_TESTS in the cmake build system, because some test takes to long to run in the android virtual device.
https://github.com/Bjoe/poco/blob/c43bc76e12ccd791913d0563328bb3874856c2bf/CMakeLists.txt#L142

- I must change the path for the test, because its not possible to write in /data/local directory on android:
https://github.com/Bjoe/poco/blob/c43bc76e12ccd791913d0563328bb3874856c2bf/Foundation/testsuite/src/GlobTest.cpp#L462

- I add a try/catch block on some tests, because some features are not implemented in android. https://github.com/Bjoe/poco/blob/c43bc76e12ccd791913d0563328bb3874856c2bf/Foundation/testsuite/src/NamedEventTest.cpp#L69
I'm not sure if this is a good approach. I was think for somebody they implement this in android and remove the NotImplementedException they see which tests are broken. But looks a bit stupid ... I don't know I need some feedback here.

**Comment by zosrothko** [comment]
@Bjoe In a similar way as other platforms, you should add POCO_OS_ANDROID to Poco/include/Platform.h and use the condition
```
#if POCO_OS == POCO_OS_ANDROID
```
instead of
```
#ifdef __ANDROID__
```

**Comment by zosrothko** [comment]
@aleks-f From my point of view, all change requests are ok. BTW, it is nice to have Poco on Android. Thanks to @Bjoe for this contribution.

**Comment by aleks-f** [comment]
@Bjoe this pull should go to [poco-1.9.0](https://github.com/pocoproject/poco/tree/poco-1.9.0)

**Comment by Bjoe** [comment]
@aleks-f Yep, I know. But I will fix first the review findings... then test should be back to green and then I will merge or better squash and rebase to poco-1.9.0. Too many changes at once could be difficult to find the problem if the build fails. So when I'm ready I will inform you. Btw. how can I requested a review?

**Comment by aleks-f** [comment]
> how can I requested a review?

image

**Comment by Bjoe** [comment]
@aleks-f I didn't have this "button" on the right site of "Reviewers".

**Comment by aleks-f** [comment]
I'm not sure why, you are a member of developers team and I think you should be able to:

https://help.github.com/articles/requesting-a-pull-request-review/

@zosrothko can you request reviews on poco pulls with your permissions?

**Comment by Bjoe** [comment]
@aleks-f I have read this article about "Requesting a pull request review" before and I didn't have this buttons or can search for a person. I think this is the problem:
> Note: Pull request authors can't request reviews unless they are either a repository owner or  collaborator with write access to the repository.

**Comment by Bjoe** [comment]
@zosrothko I used first POCO_ANDROID instead of POCO_OS_ANDROID, because it is not only to add  POCO_OS_ANDROID in Poco/Platfrom.h... see my pull request #2186

**Pull request merged**
