### PR TITLE
Added new static method to OpenSSLInitializer, disableSSLInitialization()

### PR DESCRIPTION
**Pull request by bobstabler**
This allows the caller to inform Poco that the Open SSL library has already been initialized outside of Poco, for example in main(), so it doesn't re-initialize it, and, more importantly, uninitialized it when the last OpenSSLInitializer goes out of scope.

### CODE REVIEW

**Comment by aleks-f** [comment]
Thanks for the contribution. Would you mind adding also automatic initialization like the one we have in Net and Data libraries (see [blog](http://pocoproject.org/blog/?p=741) for details.

**Comment by bobstabler** [comment]
I’ll take a look.  

P.S. If I add new files, do I have to update a whole mess of project files?

**Comment by aleks-f** [comment]
On Posix, you'll have to add the .cpp file name to Makefile. On Windows, you can only add it to a VS solution version of your choice to compile/test, I'll generate the rest of the projects. Or, if you feel inclined, try [ProGen](https://github.com/pocoproject/poco/tree/develop/ProGen) yourself ;).

**Comment by bobstabler** [comment]
Thanks.  I probably won't get to look at it for a while.

**Pull request merged**
