### PR TITLE
develop branch: MongoDB additions, improvements

### PR DESCRIPTION
**Pull request by matejk**
1. Allow using const reference to Document and Array without casting away constness to get its type.
2. Poco::MongoDB::UUID to handle BSON UUID type 0x04 (#834)
3. Pass indentation parameter to array elements
4. Handle different types of "n" attribute in the response from count request.
5. Added tests to MongoDB test suite

### CODE REVIEW

**Comment by fbraem** [comment]
I will look into this pull request and divide them in some smaller parts. Thanks @matejk  for your work!

**Comment by matejk** [comment]
I'm currently looking at some of the requests (insert, update, delete). From what I was able to find out, these use "legacy" wire protocol where the the status of the op is not returned immediately with the  request.

MongoDB 2.6 and newer have this capability.

http://docs.mongodb.org/manual/release-notes/2.6-compatibility/#write-methods-incompatibility

I was able to construct $cmd requests to create new format of insert/update requests and a function that parses the response for errors (unfortunately the response format from MongoDB is not uniform for all requests).

Would you consider integrating this functionality into Poco::MongoDB?

**Comment by fbraem** [comment]
All code that can enhance or make the MongoDB module better is acceptable. Is your code available in your Poco fork?

**Comment by matejk** [comment]
Not yet. It is currently part of the code that out of the Poco repository. It could be added to my fork in a week or two.

**Comment by fbraem** [comment]
@matejk Is there a reason why you didn't use the UUID class from POCO? This sample use this class to insert a uuid in MongoDB:

````
	Poco::UUIDGenerator uuidGenerator;
	Poco::UUID uuid = uuidGenerator.create();

	Poco::MongoDB::Database db("team");
	Poco::SharedPtr<Poco::MongoDB::InsertRequest> insertPlayerRequest = db.createInsertRequest("unique");

	Poco::MongoDB::Binary::Ptr binaryUUID = new Poco::MongoDB::Binary(128/8, 0x04);
	unsigned char szUUID[16];
	uuid.copyTo((char*) szUUID);
	binaryUUID->buffer().assign(szUUID, 16);
	insertPlayerRequest->addNewDocument().add("uuid", binaryUUID);
````

**Comment by matejk** [comment]
I did use Poco::UUID.

New class in Poco::MongoDB namespace is a wrapper implemented based on MongoDB::Binary that simplifies serialisation/deserialisation of Poco::UUID to/from BSON. It uses UUID::copyTo and UUID::copyFrom internally (https://github.com/matejk/poco/commit/0c49a1cf791b539cbb311bfc5d1b1942d5bafad8#diff-504ba91fbea1dfb0d0b4dc687719ee57R80)

Example of usage can be seen from the test suite:

```C++
static Poco::UUID uuid("0489c502-e127-4312-b629-3870c9dddc07");
player->add("an_uuid", UUID::Ptr(new UUID(uuid)));
assert(doc->isType<UUID::Ptr>("an_uuid"));
UUID::Ptr dbUuid = doc->get<UUID::Ptr>("an_uuid");
assert(dbUuid->uuid() == uuid);
```

https://github.com/matejk/poco/commit/6fab349712ec732828d0dcfc0b92b008985b2826#diff-f69e882c921b00fa06a514c950420712R110

I wanted to derive MongoDB::UUID from MongoDB::Binary first but then decided to make new class, because detection of UUID was needed in MongoDB::Document when parsing BSON.

**Comment by aleks-f** [comment]
@fbraem @matejk : what is the status of this? big pull, out of sync. merge, close? if you want it merged, it will have to be synced first

**Comment by fbraem** [comment]
The code for reading UUID in Document is not the way to go ... That way the responsibility for reading is in Document and Binary (where there is a check that something is already read). The Document class doesn't need to how to read something ... It's the responsibility for the concrete classes ...

I'll see if I can find sometime to integrate UUID (the code I posted on 3/6) into MongoDB ...

**Comment by matejk** [comment]
I agree with @fbraem that introduction of code to detect UUID in the document was not good decision from my side.

The rest of the changes are mostly minor improvements. I think that you manually merged some of them, is that correct?

**Comment by matejk** [comment]
@aleks-f: if @fbraem used all of useful improvements then this PR can be closed.

**Pull request closed without merging**
