### PR TITLE
LoongArch support

### PR DESCRIPTION
**Pull request by loongson-zn**
Add LoongArch support, please review, thanks!

### CODE REVIEW

**Comment by loongson-zn** [comment]
LoongArch is a RISC style ISA which is independently designed by Loongson Technology in China. Now we have a loongnix os base on debian 10.4, we hope this PR can be merged，thanks！
Documentations:
 - ISA:
   https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html
 - ABI:
   https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html
 - More docs can be found at:
   https://loongson.github.io/LoongArch-Documentation/README-EN.html

If you have any questions, please let me know.

**Comment by aleks-f** [comment]
@loongson-zn thanks for the contribution
for future reference: please do not send pulls against master, but devel branch
also, the double conversion header was patched, but if you want that change to be safe from being overwritten in the future, you should send it upstream to the original library - we can't afford to keep track of such things

**Comment by loongson-zn** [comment]
> @loongson-zn thanks for the contribution for future reference: please do not send pulls against master, but devel branch also, the double conversion header was patched, but if you want that change to be safe from being overwritten in the future, you should send it upstream to the original library - we can't afford to keep track of such things

Thanks @aleks-f , where isupstream to the original librar

**Comment by loongson-zn** [comment]
> @loongson-zn thanks for the contribution for future reference: please do not send pulls against master, but devel branch also, the double conversion header was patched, but if you want that change to be safe from being overwritten in the future, you should send it upstream to the original library - we can't afford to keep track of such things

Thanks @aleks-f, there isn't poco's upstream?  Where is the upstream of the original poco library？

**Comment by aleks-f** [comment]
I was referring to [double_conversion](https://github.com/google/double-conversion) header: [utils.h](https://github.com/pocoproject/poco/blob/master/Foundation/src/utils.h)

**Comment by loongson-zn** [comment]
Thanks @aleks-f

**Pull request closed without merging**
