### PR TITLE
Adds Visual Studio 2022 (v170) to buildwin.cmd

### LINKED ISSUE #3482: Visual Studio 2022 (v170) missing from buildwin.cmd
buildwin.cmd should add support for building with Visual Studio 2022

### PR DESCRIPTION
**Pull request by hmartinez82**
All solution and project files are just clones of vs160 renamed to vs170 and with the toolset updated to v143

Let me know if I missed any component

Fixes #3482

### CODE REVIEW

**Comment by hmartinez82** [comment]
@obiltschnig Will these changes be considered somewhere else? Maybe on #3493  ?

**Comment by obiltschnig** [comment]
ARM changes will come in at a later point (1.12). VS project files are generated by a tool (ProGen), so it makes no sense to manually change them. Unfortunately I don't have the time to update ProGen for 1.11.2.

**Comment by hmartinez82** [comment]
Oh, I had no idea about this ProGen 😑😅

**Comment by hmartinez82** [comment]
@obiltschnig @aleks-f I'm going to take on adding ARM64 to ProGen, unless someone is already working on it.

**Pull request closed without merging**
