### PR TITLE
Fix compile with `-DPOCO_NET_NO_IPv6`

### PR DESCRIPTION
**Pull request by gelldur**
Fixed compile with `-DPOCO_NET_NO_IPv6`

### CODE REVIEW

**Comment by gelldur** [comment]
Failing CI as I can tell is not fault of this change.

**Comment by gelldur** [comment]
@aleks-f this PR was merged to master but on current master those changes do not exist. 
https://github.com/pocoproject/poco/blob/master/Net/src/HTTPClientSession.cpp
I can't even find in [history related changes](https://github.com/pocoproject/poco/commits/master/Net/src/HTTPClientSession.cpp).

Did someone force push?  
Does `-DPOCO_NET_NO_IPv6` is still relevant ?

**Comment by aleks-f** [comment]
@gelldur I am not quite sure anymore how or why I merged this into master - nothing should go there except the releases. There's been quite a bit of discrepancies between release branches  and devel since the 1.11 series and we're still recovering from that - that's the best explanation I have.

Long story short, I am sorry for dropping this one; please send a pull to devel branch and we'll release it in 1.13.1

**Comment by gelldur** [comment]
Thank you, that is all I need. I will resubmit.

**Pull request merged**
