### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mkrivos**
cmake: reenable 'd' postfix for debug poco libraries

### CODE REVIEW

**Comment by mkrivos** [comment]
Hmm, it seems that travis has serious problem - this commit can't be intrusive ...

**Comment by bachp** [comment]
Jep travis seems to have some troubles recently :(

I had a look at your change. Do you need the "d" postfix on non Windows systems too?
Because for windows it should be set here: https://github.com/pocoproject/poco/blob/develop/cmake/DefinePlatformSpecifc.cmake#L45
Maybe you can explain the problem you were facing?

@obiltschnig Do the Makefiles also create "d" sufixes? I suggest we should try to keep the CMake output consistent with the Makefile/MSProject outputs as much as possbile.

**Comment by obiltschnig** [comment]
Yes, the Makefiles create a "d" suffix for debug builds of libraries.

**Comment by bachp** [comment]
Ok I was not aware of that.
 I would suggest the following solution then:
https://github.com/siemens/poco/commit/28ac7e80dbd1de8515b827bcb84b14c59c3d547f

@mkrivos Could you check if this solves your problem?

**Comment by mkrivos** [comment]
Seems to be OK.

**Pull request closed without merging**
