### PR TITLE
C++11 support #1793

### PR DESCRIPTION
**Pull request by aleks-f**
this goes into develop, then 2.0 release.
1.8.x will be last major non-c++11 release
	
- [x] All changes are protected by defines POCO_ENABLE_CPP11 and POCO_ENABLE_CPP14		
- [x] Replace std::auto_ptr with std::unique_ptr		
- [x] SharedPtr inherits from std::shared_ptr		
- [x] AtomicCounter inherits from std::atomic_int		
- [x] Array inherits from std::array		
- [x] Move semantics for SharedPtr, AutoPtr, Buffer, Message, JSON::Object and JSON::Array		
- [x] Use <cstdint> for int types		
- [x] Clock and Timestamp uses <chrono>		
- [x] Use std::mutex* for Mutex instead of platform specific		
- [x] Use std::condition_variable for Event instead of platform specific		
- [x] Use std::thread for Thread instead of platform specific		
- [x] Use template variadic for Poco::format and Logger::* instead of lots of overloads		
- [x] StdFunctionDelegate for basic events		
- [x] std::thread doesn`t support priority setting
- ~~[ ] std::tuple instead of Tuple: std::tuple doesn't accept partial initialization~~
- ~~[ ] Semaphore: simulated with mutex and condition variable, but platform specific should be better~~
- ~~[ ] RWLock: std::shared_timed_mutex has separate read and write unlock, but RWLock uses unlock for both~~
- ~~[ ] Use <random> for Poco/Random, but it supports 4 different modes that must be mapped~~
- [x] replace JSON parser
- [ ] Crypto PKCS12 and ECC support

### CODE REVIEW

**Comment by aleks-f** [comment]
@obiltschnig this is initial attempt, probably there will be changes before merging; in any case, I propose to squash the merge into develop

**Comment by RangelReale** [comment]
There is a cpp11_changes.txt
<https://github.com/pocoproject/poco/pull/1795/files#diff-fb19503442f6a4845175edbd07e14287>
file
on the root folder which lists all the c++11 changes I made, and also the
potential TODO and problems.

**Comment by aleks-f** [comment]
@obiltschnig I'm trying to translate the list mentioned above to the project cards but for some reason it only allowed me to do one, now it says "awaiting triage", whatever that means, not sure if it has to do with project ownership or something

another thing, I think we could drop the c++11 macro and only carry on c++14/17 for 2.0?

**Comment by aleks-f** [comment]
worked now, [project](https://github.com/pocoproject/poco/projects/1) updated

**Comment by aleks-f** [comment]
this is going to be merged into develop soon, the outstanding items on the list will likely be turned into issues for post-2.0 release

**Comment by aleks-f** [comment]
@zosrothko do you know why this is happening on travis?
```
E: Failed to fetch http://apt.llvm.org/trusty/dists/llvm-toolchain-trusty/main/source/Sources  404  Not Found [IP: 52.11.249.247 80]
```

**Comment by zosrothko** [comment]
@aleks-f It seems that LLVM decided to remove all pre 4.0 version of clang from thair distribution web site
```
gcc backport (ppa) is necessary on Trusty (for libstdc++).
Precise, Quantal, Raring, Saucy and Utopic are no longer supported by Ubuntu.

Trusty (14.04) - Last update : Mon, 04 Sep 2017 06:34:06 UTC / Revision: 312462

deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main
deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty main
# 4.0 
deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main
deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main
# 5.0 
deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main
deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main

# Also add the following for the appropriate libstdc++
deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main, so that only the 4.0, 5.0 and upper version remain.
```

**Pull request merged**
