### PR TITLE
MongoDB::Array interface improvements (on top of 1.11.2)

### PR DESCRIPTION
**Pull request by matejk**
Two improvements:

* Use std::size_t instead of int in get function to be consistent with type returned from size()
* Array-specific add functions that automatically set stringified sequence number for element name to simplify adding members to array
* added test function for MongoDB array

### CODE REVIEW

**Comment by matejk** [comment]
@obiltschnig: This PR replaces #3013.

**Comment by matejk** [comment]
Rebased to 1.11.2.

**Comment by aleks-f** [comment]
@matejk sorry for being so unresponsive, this should go into 1.12.0 release

**Comment by matejk** [comment]
@aleks-f, no problem. I know that this is not the most important PR.

**Pull request merged**
