### PR TITLE
Configuration to receive OCSP stapling response for client connection…

### PR DESCRIPTION
**Pull request by p-neels**
1. Configuration to receive OCSP stapling response for client connections 
2. Callback implementation to verify the response if the server returns any response

### CODE REVIEW

**Comment by p-neels** [comment]
@obiltschnig  Please find the new pull request raised against devel branch. Added all the required  checks in the call back implementation to verify the received OCSP response.

**Comment by p-neels** [comment]
@obiltschnig  any updates on this pull request?

**Comment by obiltschnig** [comment]
Made some changes for style and also checked OpenSSL version (1.0.2 min).
See 7ca90cb0c34a884c450d6d7e59ccef36d442e930
Hope we have the memory management in `verifyOCSPResponseCallback()` right.

**Comment by p-neels** [comment]
> Made some changes for style and also checked OpenSSL version (1.0.2 min).
> See [7ca90cb](https://github.com/pocoproject/poco/commit/7ca90cb0c34a884c450d6d7e59ccef36d442e930)
> Hope we have the memory management in `verifyOCSPResponseCallback()` right.

@obiltschnig Yep have done the required long run testing to make sure no memory leaks.
Thanks for the update

**Comment by obiltschnig** [comment]
Manually merged into poco-1.11.0

**Pull request merged**
