### PR TITLE
epoll() is absent on AIX (1.9.1)

### PR DESCRIPTION
**Pull request by agalanin**
Re-fix of #2559 for 1.9.1 branch.

### CODE REVIEW

**Comment by agalanin** [comment]
> @agalanin Could you also backport your fix on the develop branch? TIA

It's difficult because there are many compilation errors on develop branch.

**Comment by zosrothko** [comment]
@agalanin On which platform?

**Comment by zosrothko** [comment]
What commands are you using (configure, make)?

**Comment by agalanin** [comment]
> 
> 
> What commands are you using (configure, make)?

See https://github.com/pocoproject/poco/pull/2682 and https://github.com/pocoproject/poco/issues/2683.

**Comment by obiltschnig** [comment]
Please re-target for poco-1.10.0 branch.

**Comment by agalanin** [comment]
> @agalanin Could you also backport your fix on the develop branch? TIA

As of commit 59ac3451684c6cf97a6c72b233264bc58ad2e3dd this fix is not needed. AIX compilation succeded after applying a patch from #2682.

**Pull request closed without merging**
