### PR TITLE
c++11 thread priority and affinity, and more

### PR DESCRIPTION
**Pull request by RangelReale**
Please review if the way I did the std::thread platform-specific code is acceptable, for VX I just copy-pasted, so it is not tested.

* c++11 thread priority and affinity
* AtomicCounter wasn't using std::atomic
* Buffer wasn't setting all fields on move
* Poco::Event is not directly available in c++11, keep using the native versions
* UnWindows.h define NOMINMAX to reduce conflicts
* Remove "-static" from Linux GCC parameters, this conflicts with c++11 classes (https://stackoverflow.com/questions/7090623/c0x-thread-static-linking-problem)
* Link "-lrt" before "-lpthread" on Linux, otherwise won't build on GCC 5+

### CODE REVIEW

**Comment by RangelReale** [comment]
Tested on Windows, Ubuntu 14.04 and Ubuntu 16.04

**Comment by zosrothko** [comment]
@RangelReale Tested on Windows. Which VS compiler? Which gcc compiler? Which clang compiler?

**Comment by RangelReale** [comment]
VS2015 x86, GCC 4.8.5, GCC 5.4.0

**Comment by zosrothko** [comment]
Travis CI is failing on CMake with gcc 5.4.1:  [Job #2726.3](https://travis-ci.org/pocoproject/poco/jobs/252905916)
```
In file included from /home/travis/build/pocoproject/poco/Foundation/src/Thread_STD.cpp:30:0,
                 from /home/travis/build/pocoproject/poco/Foundation/src/Thread.cpp:26:
/home/travis/build/pocoproject/poco/Foundation/src/Thread_STD_POSIX.cpp: In member function ‘void Poco::ThreadImpl::setAffinityImpl(int)’:
/home/travis/build/pocoproject/poco/Foundation/src/Thread_STD_POSIX.cpp:150:68: error: cannot convert ‘std::unique_ptr<std::thread>’ to ‘pthread_t {aka long unsigned int}’ for argument ‘1’ to ‘int pthread_setaffinity_np(pthread_t, size_t, const cpu_set_t*)’
  if (pthread_setaffinity_np(_pData->thread, sizeof(cpuset), &cpuset) != 0)
                                                                    ^
/home/travis/build/pocoproject/poco/Foundation/src/Thread_STD_POSIX.cpp: In member function ‘int Poco::ThreadImpl::getAffinityImpl() const’:
/home/travis/build/pocoproject/poco/Foundation/src/Thread_STD_POSIX.cpp:186:68: error: cannot convert ‘const std::unique_ptr<std::thread>’ to ‘pthread_t {aka long unsigned int}’ for argument ‘1’ to ‘int pthread_getaffinity_np(pthread_t, size_t, cpu_set_t*)’
  if (pthread_getaffinity_np(_pData->thread, sizeof(cpuset), &cpuset) != 0)
```

**Comment by RangelReale** [comment]
Ops, missed some ->native_handler() calls

**Comment by zosrothko** [comment]
Didn't you miss also the failure on OSX?

```
$ $CXX --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
...
In file included from src/Thread_STD.cpp:30:
src/Thread_STD_POSIX.cpp:160:2: error: unknown type name 'kern_return_t'
        kern_return_t ret;
        ^
src/Thread_STD_POSIX.cpp:161:2: error: unknown type name 'thread_affinity_policy'
        thread_affinity_policy policy;
        ^
src/Thread_STD_POSIX.cpp:166:4: error: use of undeclared identifier 'thread_policy_t'
                (thread_policy_t)&policy,
                 ^
src/Thread_STD_POSIX.cpp:165:3: error: use of undeclared identifier 'THREAD_AFFINITY_POLICY'
                THREAD_AFFINITY_POLICY,
                ^
src/Thread_STD_POSIX.cpp:167:3: error: use of undeclared identifier 'THREAD_AFFINITY_POLICY_COUNT'
                THREAD_AFFINITY_POLICY_COUNT);
                ^
src/Thread_STD_POSIX.cpp:168:13: error: use of undeclared identifier 'KERN_SUCCESS'
        if (ret != KERN_SUCCESS)
                   ^
src/Thread_STD_POSIX.cpp:205:2: error: unknown type name 'kern_return_t'
        kern_return_t ret;
        ^
src/Thread_STD_POSIX.cpp:206:2: error: unknown type name 'thread_affinity_policy'
        thread_affinity_policy policy;
        ^
src/Thread_STD_POSIX.cpp:207:2: error: unknown type name 'mach_msg_type_number_t'
        mach_msg_type_number_t count = THREAD_AFFINITY_POLICY_COUNT;
        ^
src/Thread_STD_POSIX.cpp:207:33: error: use of undeclared identifier 'THREAD_AFFINITY_POLICY_COUNT'
        mach_msg_type_number_t count = THREAD_AFFINITY_POLICY_COUNT;
                                       ^
src/Thread_STD_POSIX.cpp:208:2: error: unknown type name 'boolean_t'
        boolean_t get_default = false;
        ^
src/Thread_STD_POSIX.cpp:211:4: error: use of undeclared identifier 'thread_policy_t'
                (thread_policy_t)&policy,
                 ^
src/Thread_STD_POSIX.cpp:210:3: error: use of undeclared identifier 'THREAD_AFFINITY_POLICY'
                THREAD_AFFINITY_POLICY,
                ^
src/Thread_STD_POSIX.cpp:214:13: error: use of undeclared identifier 'KERN_SUCCESS'
        if (ret != KERN_SUCCESS)
                   ^
14 errors generated.
make[1]: *** [/Users/travis/build/pocoproject/poco/Foundation/obj/Darwin/x86_64/debug_shared/Thread.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Foundation-libexec] Error 2
```

**Comment by RangelReale** [comment]
Hmm didn't test in OSX, must be some includes missing. I will test and fix these today.

**Comment by RangelReale** [comment]
Fixed OSX

**Comment by zosrothko** [comment]
@aleks-f I did not check/review this PR and have no time for now. I will check the removal of the -STATIC options beginning of August.

**Comment by aleks-f** [comment]
that's ok, I merged it so we don't fall out of sync and end up with many conflicts again - c++11 branch is currently volatile anyway

**Pull request merged**
