### PR TITLE
AppVeyor with msbuild & embedded openssl & AppVeyor reporting panels

### PR DESCRIPTION
**Pull request by zosrothko**
Hi

This PR provides the following points:
1/ Switch building tool from CMake to msbuild with the buildwin.cmd script
2/ Report of warning & error on the AppVeyor Message panel
3/ Chack for FIXME, TODO, HACK in *.cpp sources
3/ Fast fail , ie.the build fails at the first failed job
4/ Use of embedded openssl
5/ Improved test launching in powershell with report to the AppVeyor Test panel

There are a lot of minor commits go and rollback because setting up AppVeyor scripts can be done only remotly with commit.

Results can be viewed here: https://ci.appveyor.com/project/zosrothko/poco

### CODE REVIEW

**Comment by obiltschnig** [comment]
Is it possible, as with Travis, to also do a CMake build. I'd like to have both covered.

**Comment by zosrothko** [comment]
Ok, I will add the CMake....  build & test or only build?

**Comment by obiltschnig** [comment]
Running tests as well would be good, I guess. Should I merge this pull request first or will you submit a new one containing all changes?

**Comment by zosrothko** [comment]
It would be good to merge now so that other commits & PR could benefit from the new version.

**Pull request merged**
