### PR TITLE
Set custom active port in FTPClientSession

### PR DESCRIPTION
**Pull request by micheleselea**

### CODE REVIEW

**Review by aleks-f — CHANGES_REQUESTED** [review]
please redirect this pull to devel branch

**Comment by aleks-f** [comment]
@micheleselea do you plan to change this as requested or can I close it?

**Comment by micheleselea** [comment]
Hi @aleks-f I think I forgot to put this in devel branch, I'll do it, because in some application, if you need active ftp connection you need to set a specific port for enable it on a firewall (for example)

**Comment by matejk** [comment]
Hi @micheleselea, can you please prepare this pull request for branch devel?

**Comment by micheleselea** [comment]
ok

**Comment by matejk** [comment]
@micheleselea , can you please rebase this PR on branch `main`, please?

**Pull request closed without merging**
