### PR TITLE
Fully support cross-compiling with Linux GNU build system using OSARCH_64BITS=[0,1]

### PR DESCRIPTION
**Pull request by kblaschke**
Building POCO on a Linux host with an architecture different from the host system's (e. g. using `--cflags="-m32"`), dynamic linking of the POCO libraries fails. This patch adds the proper compiler and linker flags to the Linux configuration (including auto.detection of the host's arch if not specified), and passes `LINKFLAGS` to the dynamic linker command line.

Note: The build/rules/global script always adds either `*FLAGS32` or `*FLAGS64` to the flags list, and defaults to the 32-bit variant if `OSARCH_64BITS` is undefined. I left the file unchanged to avoid possible problems with other OS configurations.

This patch will fix issue #894

### CODE REVIEW

**Comment by RangelReale** [comment]
This patch breaks static library building, because it passes -m32 / -m64 to "ar", which doesn't recognize this parameter.

**Comment by zosrothko** [comment]
The -m32 and -m64 options are targeting generation on an 32 bit arch and 64 arch respectively. Since those options are used at generation time, they should be added IMO to CFLAGS32/64 and CXXFLAGS32/64 only .

**Comment by kblaschke** [comment]
The (GNU) linker also needs the architecture parameter to determine the libraries which need to be linked. If not given, the linker will use the first library found in it's search path (mostly the native system arch) and try to use it to link the compiled object files, which will naturally fail if these were generated with a different arch. Passind either CFLAGS or CXXFLAGS to the linker will mostly work, but the linker doesn't accept some compiler arguments and vice versa.

There should be four separate flag lists, each with 32/64 suffixes:
- CFLAGS for the C ompiler
- CXXFLAGS for the C++ compiler
- LDFLAGS for the dynamic linker
- LINKFLAGS for the static linker/archiver

**Comment by aleks-f** [comment]
ok, can you submit a pull fixing that?

**Comment by zosrothko** [comment]
Its already in the branch develop except that the -m32/m64 options should be removed from LIBFLAGS32/64.

SHLIBFLAGS32/64 goes for linking a shared library used by rule/lib
LINKFLAGS32 goes for linking a executable used by rule/exec

One should add also DYLIBFLAGS32/64 for building a dynamicaly loadable lib.

**Pull request merged**
