### PR TITLE
New XmlStream API

### PR DESCRIPTION
**Pull request by mkrivos**
Pocoized library from http://www.codesynthesis.com/projects/libstudxml/ + tests.
Any ideas to improve this patch are welcomed.

### CODE REVIEW

**Comment by mkrivos** [comment]
Compiles Ok on linux64 gcc 4.9.3 and win64 vs 2013

**Comment by mkrivos** [comment]
For now, I am done.

**Comment by obiltschnig** [comment]
Need to check with libstudxml authors if it's OK to re-license under Boost instead of MIT license.

**Comment by obiltschnig** [comment]
Got the OK to use the Boost license from the libstudxml author.

**Comment by obiltschnig** [comment]
One other issue: should we really include the serialization part (based on genX). It's API is not much different from the XMLWriter, so I wonder if it makes sense pulling in additional external dependencies (genX), which we'll have to maintain, etc.

**Comment by mkrivos** [comment]
Ok, can I remove Serializer part ?

**Comment by obiltschnig** [comment]
Yes, please remove the serializer part including genX.

**Comment by mkrivos** [comment]
Done

**Comment by obiltschnig** [comment]
Made some more style fixes today. Also, we can get rid of the QName class. It's equivalent to the existing Name class. See #923

**Comment by mkrivos** [comment]
Ok I can look at, but at sanday because I'm on vacation for now.

**Comment by obiltschnig** [comment]
Don't worry, I'll take care of that.

**Pull request merged**
