### PR TITLE
Add SHA2 algorithm

### PR DESCRIPTION
**Pull request by OgreTransporter**
Add SHA2 algorithm because MD5 and SHA1 are not secure anymore.

### CODE REVIEW

**Comment by obiltschnig** [comment]
Has this code been written entirely by you, or is it based on some other implementation. If so, we'll need to be careful about the license and add some acknowledgement.

**Comment by OgreTransporter** [comment]
I've added license information to the files. The code is based on the implementation of mbed TLS (Apache 2.0, http://www.apache.org/licenses/LICENSE-2.0)

**Comment by obiltschnig** [comment]
Aand, would you mind adding a test case. Just like [SHA1EngineTest.cpp](https://github.com/pocoproject/poco/blob/develop/Foundation/testsuite/src/SHA1EngineTest.cpp), but with the correct test vectors.

**Comment by OgreTransporter** [comment]
Give me a few minutes ;-)

**Comment by OgreTransporter** [comment]
Done ;-)

**Comment by obiltschnig** [comment]
Thank you!

**Comment by OgreTransporter** [comment]
You're welcome! I'm working on an implementation of SHA3, too.

**Comment by OgreTransporter** [comment]
https://github.com/pocoproject/poco/pull/1664

**Pull request merged**
