### PR TITLE
App veyor close to be complete

### PR DESCRIPTION
**Pull request by zosrothko**
Hi

This PR brings a quasi complete CI of Poco on AppVeyor.for the environements msbuild, Cygwin and CMake as displayed below Testsuite are run only in the release shared  configuration for msbuild.

Environment: builder=msbuild, vsver=120, linkmode=shared; Platform: Win32
Environment: builder=msbuild, vsver=120, linkmode=shared; Platform: x64
Environment: builder=msbuild, vsver=120, linkmode=static_md; Platform: Win32
Environment: builder=msbuild, vsver=120, linkmode=static_md; Platform: x64
Environment: builder=msbuild, vsver=120, linkmode=static_mt; Platform: Win32
Environment: builder=msbuild, vsver=120, linkmode=static_mt; Platform: x64
Environment: builder=msbuild, vsver=140, linkmode=shared; Platform: Win32
Environment: builder=msbuild, vsver=140, linkmode=shared; Platform: x64
Environment: builder=msbuild, vsver=140, linkmode=static_md; Platform: Win32
Environment: builder=msbuild, vsver=140, linkmode=static_md; Platform: x64
Environment: builder=msbuild, vsver=140, linkmode=static_mt; Platform: Win32
Environment: builder=msbuild, vsver=140, linkmode=static_mt; Platform: x64
Environment: builder=cmake, vsver=120; Platform: Win32
Environment: builder=cmake, vsver=120; Platform: x64
Environment: builder=cmake, vsver=140; Platform: Win32
Environment: builder=cmake, vsver=140; Platform: x64
Environment: builder=cygwin; Platform: Win32
Environment: builder=cygwin; Platform: x64

What remain to do
integration of the testsuite of Redis (Redsi not yet available on Windows)
integration of the testuite of Poco/Data that loops for an unknown reason
the completion of  the CMake build with the integrated openssl stuff (to do by a CMake specialist)

Beware that the overall time to run a complete build is about 12 hours....

### CODE REVIEW

**Comment by aleks-f** [comment]
@zosrothko: appveyor failed

**Comment by zosrothko** [comment]
AppVEyor fails on a timeout after 2 hours on a exception from downloading PostgreSQL
As owner of pocoproject, you can relaunch the full build

Installing C:\Program Files (x86)\PostgreSQL\9.4 ... 
Downloading... 
Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At line:11 char:5
+     (New-Object Net.WebClient).DownloadFile('http://get.enterprisedb.com/postgre ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Installing...

**Comment by bachp** [comment]
@zosrothko Could you elaborate what's the problem you mean with "the completion of the CMake build with the integrated openssl stuff (to do by a CMake specialist)" maybe I can help.

**Comment by zosrothko** [comment]
@bachp There is already an issue opened for this problem: #1093 . Change should be made to CMake so that the build uses the embedded openssl instead of the standard OpenSSL libs

**Pull request merged**
