### PR TITLE
Proposed changes for fixing NetSSL_OpenSSL and adding portability function in Sharedmemory

### PR DESCRIPTION
**Pull request by zosrothko**
Hi

here follow proposed changes for fixing NetSSL_OpenSSL compilation of TLSv1_1 and TLSv1_2.

The SahredLibrary::getOSName(const std::string& name) bring a better portability in SharedMemory for naming the real OS dependent library. For exemple, getOSName("FOO") will return

on Linux/Unix:   libFOO.so
on Cygwin        cygFOO.dll
on Windows      FOO.dll 

so that loading(getOSName("FOO")) will work on all platforms.

May be it would be also interesting to add an paramter asto the suffix function as suffix( const char* version = NULL) so that the version numbering be handled properly.

### CODE REVIEW

**Comment by zosrothko** [comment]
Yes, I have rollbacked to the inital version and fix the  guarded TLSv1_1/TLSv1_2 code in Context.cpp

**Comment by zosrothko** [comment]
May be it is ok for you to change the status of the Cygwin port from Experimental to Operational??

**Comment by aleks-f** [comment]
I'm not sure I'm following - this pull includes poco embedded headers and I can't see that changed. As for change to operational - where, in the documentation?

**Comment by zosrothko** [comment]
Sorry to be vague about, but I was talking about the status of the Cygwin port on the Wiki page  (by the way, I have updated it)

**Pull request merged**
