### PR TITLE
Redis Module

### PR DESCRIPTION
**Pull request by fbraem**
This is a Redis client for Poco. All tests passes on Linux 64-bit. The code compiles on Windows (64-bit) but I can't test it because I have no connection from my Windows platform to a Redis server. There is still some work to do for Windows: create the missing VS studio workspaces.

### CODE REVIEW

**Comment by aleks-f** [comment]
Thank you Franky, good contribution. There were some problems with Travis, I assume this failed build has to do with that. I'll merge; if it still fails, please take a look and fix it.

**Comment by zosrothko** [comment]
travis.yml is missing the Redis server, just add redis-server to the service block, as below

services:
  - mongodb
  - redis-server

**Comment by zosrothko** [comment]
By the way, IMO the Redis project -- as well as the MongoDB -- should go under the main Data directory. There are already accessors to MySQL, SQLite and ODBC, so it would be cleaner to put Redis and MongoDB here also. could you try it for Redis?

**Comment by obiltschnig** [comment]
No, only projects that are actually based on the Data library such as MySQL and ODBC should go under Data.

**Comment by zosrothko** [comment]
Ok got it...

**Comment by aleks-f** [comment]
Strictly speaking, more proper name for Data would have been SQL, but it's too late for it now ...

**Comment by zosrothko** [comment]
got an unresolved external reference when build Redis/testsuite with CMake
Linking CXX executable ..\..\bin\Redis-testrunner.exe
RedisTest.cpp.obj : error LNK2019: symbole externe non rÚsolu "public: class std::basic_string<char,struct std::char_traits<char>,class
 std::allocator<char> > __thiscall Poco::Redis::RedisInputStream::getline(void)" (?getline@RedisInputStream@Redis@Poco@@QAE?AV?$basic_s
tring@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) rÚfÚrencÚ dans la fonction "public: static void __cdecl Poco::Redis::RedisTypeT
raits<class Poco::Nullable<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > >::read(class Poco
::Redis::RedisInputStream &,class Poco::Nullable<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char>
> > &)" (?read@?$RedisTypeTraits@V?$Nullable@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Poco@@@Redis@Poco@@SAXAAVRe
disInputStream@23@AAV?$Nullable@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@3@@Z)
RedisTest.cpp.obj : error LNK2019: symbole externe non rÚsolu "__declspec(dllimport) public: __thiscall Poco::Redis::PooledConnection::
PooledConnection(class Poco::ObjectPool<class Poco::Redis::Client,class Poco::SharedPtr<class Poco::Redis::Client,class Poco::Reference
Counter,class Poco::ReleasePolicy<class Poco::Redis::Client> >,class Poco::PoolableObjectFactory<class Poco::Redis::Client,class Poco::
SharedPtr<class Poco::Redis::Client,class Poco::ReferenceCounter,class Poco::ReleasePolicy<class Poco::Redis::Client> > > > &,long)" (_
_imp_??0PooledConnection@Redis@Poco@@QAE@AAV?$ObjectPool@VClient@Redis@Poco@@V?$SharedPtr@VClient@Redis@Poco@@VReferenceCounter@3@V?$Re
leasePolicy@VClient@Redis@Poco@@@3@@3@V?$PoolableObjectFactory@VClient@Redis@Poco@@V?$SharedPtr@VClient@Redis@Poco@@VReferenceCounter@3
@V?$ReleasePolicy@VClient@Redis@Poco@@@3@@3@@3@@2@J@Z) rÚfÚrencÚ dans la fonction "public: void __thiscall RedisTest::testPool(void)" (
?testPool@RedisTest@@QAEXXZ)
RedisTest.cpp.obj : error LNK2019: symbole externe non rÚsolu "__declspec(dllimport) public: virtual __thiscall Poco::Redis::PooledConn
ection::~PooledConnection(void)" (__imp_??1PooledConnection@Redis@Poco@@UAE@XZ) rÚfÚrencÚ dans la fonction "public: void __thiscall Red
isTest::testPool(void)" (?testPool@RedisTest@@QAEXXZ)
RedisTest.cpp.obj : error LNK2019: symbole externe non rÚsolu "__declspec(dllimport) public: __thiscall Poco::Redis::PooledConnection::
operator class Poco::SharedPtr<class Poco::Redis::Client,class Poco::ReferenceCounter,class Poco::ReleasePolicy<class Poco::Redis::Clie
nt> >(void)" (__imp_??BPooledConnection@Redis@Poco@@QAE?AV?$SharedPtr@VClient@Redis@Poco@@VReferenceCounter@3@V?$ReleasePolicy@VClient@
Redis@Poco@@@3@@2@XZ) rÚfÚrencÚ dans la fonction "public: void __thiscall RedisTest::testPool(void)" (?testPool@RedisTest@@QAEXXZ)
..\..\bin\Redis-testrunner.exe : fatal error LNK1120: 4 externes non rÚsolus

**Comment by fbraem** [comment]
Weird, I also use CMake together with KDevelop 4 and I don't have this problem ...

**Comment by zosrothko** [comment]
I am using the command below
Z:\git\poco\cmake-build>cmake ../. -DCMAKE_BUILD_TYPE=Release -G"NMake Makefiles" -DENABLE_TESTS=ON -DENABLE_SAMPLE=ON -DCMAKE_INSTALL_
PREFIX=..\install

**Comment by fbraem** [comment]
I'm able to build Redis module with VS 2008. I'm currently not allowed to install CMake on my Windows laptop, so I can't test your setup ...

**Pull request merged**
