### PR TITLE
Fix missing OpenSSL dependency

### PR DESCRIPTION
**Pull request by Bjoe**
Should fix issue #3245

### CODE REVIEW

**Comment by Bjoe** [comment]
This should also merge into `poco-1.10.2` and `devel` ...

**Comment by aleks-f** [comment]
> This should also merge into `poco-1.10.2` and `devel` ...

but why to 1.10.1? That is already released, so nothing goes there anymore

**Comment by andy9a9** [comment]
Duplicate of #3157

**Comment by strahlc** [comment]
@aleks-f , @Bjoe please merge #3157 instead

**Pull request closed without merging**
