### PR TITLE
MongoDB enhancements

### LINKED ISSUE #1051: MongoDB Tests on Mac don't fail gracefully
On Mac (Yosemite), with 1.6.1, I'm seeing the `MongoDBTest` throw an `InvalidArgumentException` when the `suite()` method creates the *second* `MongoDBTest` object. The first object attempts to connect to `localhost:27017` and fails, because I don't have a MongoDB running. This seems to leave the underlying `_mongo` `MongoDB::Connection` (specifically the socket I think) in a weird state, which - because it is global - causes the second constructor call to fail with the `InvalidArgumentException`. If `_mongo.disconnect()` is called upon failure, the socket seems to get itself into a nice state and the creation of the other objects fails gracefully, and all of the tests are skipped as expected (with one exception - see below). It seems very strange to me to have one global `MongoDB::Connection` object, which is modified by each of the constructors, only to then be used by the tests one at a time (but after the other test constructors have modified it). Surely the `MongoDBTest` object owning the connection and the `_connected` bool would make more sense?

For some reason this failure doesn't occur on Linux.

On a related note, the `ConnectionPool` test doesn't catch the `ConnectionRefusedException` (and doesn't skip itself if `_connected` is false), so that still fails the tests.

### PR DESCRIPTION
**Pull request by fbraem**
Fixes #1051 and #1062

### CODE REVIEW

**Comment by aleks-f** [comment]
@bufferoverflow there's AppVeyor cmake install error: 
```
cinst cmake
Installing the following packages:
cmake
By installing you accept licenses for the packages.
cmake not installed. An error occurred during installation:
 The remote server returned an error: (500) Internal Server Error.
The install of cmake was NOT successful.
cmake not installed. An error occurred during installation:
 The remote server returned an error: (500) Internal Server Error.
```

**Comment by aleks-f** [comment]
@zosrothko : are you familiar with AppVeyor?

**Comment by zosrothko** [comment]
No, but I am learning... as for Travis and PowerShell... I am working full time 5d/week on Poco since 2 months...

AppVeyor is working fine now for cmake... Can you have a look on hte Poco build #113,  running an updated version of appveyor.yml ...

**Comment by aleks-f** [comment]
for #113 see with @fbraem. obviously failed tests are not something we want

**Comment by zosrothko** [comment]
Sure but there is an issue with Poco/CMake/CTest configuration

In release mode, 2 of the 3 failing tests are the testProxy from NetSSL
: There were 2 errors: 
7:  1: class CppUnit::TestCaller<class HTTPSClientSessionTest>.testProxy
7:     "class Poco::Net::HTTPException: HTTP Exception"
7:     in "<unknown>", line -1
7:  2: class CppUnit::TestCaller<class HTTPSStreamFactoryTest>.testProxy
7:     "class Poco::Net::HTTPException: HTTP Exception"
7:     in "<unknown>", line -1

The point is that there is no way to exclude those 2 tests from the run. CTest can exclude only component, but not some tests from one component as on Travis.

The 3rd test failing in in Foundation
There was 1 failure: 
1:  1: class CppUnit::TestCaller<class TimedNotificationQueueTest>.testDequeue
1:     "ts1.elapsed() >= 0"
1:     in "C:\projects\poco-olq4c\Foundation\testsuite\src\TimedNotificationQueueTest.cpp", line 97

So I do not see a proper solution except surrounding the testProxy by a try/catch HTTPException displaying the what() when no proxy is avalable.

Note also that for now, none of the Data tests are run.. and also that the current appveyor.yml is not running any test at all... that's why appveyor is always green

**Comment by aleks-f** [comment]
is #1047 adding tests to AppVeyor? In regards to proxy test failing, I don't think it is expected to fail

**Comment by zosrothko** [comment]
NetSSL/testProxy is failing on my local win7 with VS2013 debug & release with the below exception
`testProxy: HTTP Exception: Cannot establish proxy connection: Forbidden`

It is also failing on travis and has been excluded from the travis. See travis/runtets.sh
`export CPPUNIT_IGNORE="\
  N7CppUnit10TestCallerI8PathTestEE.testExpand \
  N7CppUnit10TestCallerI13RawSocketTestEE.testEchoIPv4 \
  N7CppUnit10TestCallerI13RawSocketTestEE.testSendToReceiveFromIPv4 \
  N7CppUnit10TestCallerI14ICMPClientTestEE.testPing \
  N7CppUnit10TestCallerI22HTTPSClientSessionTestEE.testProxy \
  N7CppUnit10TestCallerI22HTTPSStreamFactoryTestEE.testProxy \
  N7CppUnit10TestCallerI19MulticastSocketTestEE.testMulticast \
  N7CppUnit10TestCallerI13NTPClientTestEE.testTimeSync"`

**Comment by aleks-f** [comment]
try to run as administrator

**Comment by zosrothko** [comment]
Same result
Z:\git\poco>build\script\runtests2.cmd NetSSL_OpenSSL Proxy


****************************************
*** NetSSL_OpenSSL
****************************************


testProxy: HTTP Exception: Cannot establish proxy connection: Forbidden

BTW, I have no idea if running with administrator UAC on AppVeyor is possible...but IMO, it would be better to fix this testProxy without admin UAC.

**Comment by aleks-f** [comment]
I have never encountered problem with proxy. UAC was needed only for ping because it uses raw sockets.

**Comment by zosrothko** [comment]
@obiltschnig @aleks-f Could you check those 2 testProxy from NetSSL_OpenSSL/testsuite and adapt them at your convenience so that they do not failed when no proxy are defined/activated/running?

`HTTPSClientSessionTest>.testProxy`
`HTTPSStreamFactoryTest>.testProxy`

**Comment by zosrothko** [comment]
Foundation\testsuite\src\TimedNotificationQueueTest.cpp failure has been fixed, thus it remains only the 2 testProxy failures to fix for a complete successful round on AppVeyor for release mode.

**Comment by aleks-f** [comment]
Ok, those are failing just for NetSSL, right?

**Comment by zosrothko** [comment]
Yes only NetSSL

**Pull request merged**
