### PR TITLE
PocoCppUnit: make CppUnit a component of Poco

### PR DESCRIPTION
**Pull request by zosrothko**
Hi

This PR provides fixes for transforming the project CppUnit as a first class citizen of Poco as the other components. builded libs are now becoming prefixed by PocoCppUnit instead CppUnit so that no clash will appear with the original CppUnit.

1/ CppUnit/include/CppUnit becomes CppUnit/include/Poco/CppUnit
2/ All Poco tests & related sources are updated
3/ Cmake is aligned and build is ok as well as the unittests using ctest
4/ GNU Make is updated and build is ok as well as the unittets and install
5/ PocoGen templates for testunit subprojects are updated but not tested
6/ The VS2013 Win32 & x64  solutions/projects are modified & tested locally so that AppVeyor can run
7/ What is missing is a complete regenaration of all vs(x) projects
8/ mkdoc & mkrelease will be updated once this PR merged in the develop branch

### CODE REVIEW

**Comment by aleks-f** [comment]
we have conflicts not, can you merge latest develop and resubmit. I was going to look into this and generate VS projects, but did not have a chance yet

**Comment by zosrothko** [comment]
Ther are problems with Travis... none of the push on branches and PR are triggering a run...

**Comment by zosrothko** [comment]
The Travis ckeck fails only on OSX because the database services are not available yet on OSX

$ sudo service mongodb start
sudo: service: command not found
$ sudo service redis-server start
sudo: service: command not found
$ sudo service mysql start
sudo: service: command not found
...
12 runs, 2 failed.

Failed: MongoDB
Failed: Redis

This is already fixed in another PR to come soon

**Comment by zosrothko** [comment]
Travis & AppVeyor are o. You could try the regeneration.

**Comment by aleks-f** [comment]
merged dev and created [new pull](https://github.com/pocoproject/poco/pull/1177)

**Pull request closed without merging**
