### PR TITLE
Stack trace

### PR DESCRIPTION
**Pull request by aleks-f**

### CODE REVIEW

**Comment by aleks-f** [comment]
@siren186 if you care to do the windows, feel free to do so. see #4692

**Comment by siren186** [comment]
@aleks-f OK, Got it. Today is the first day of the Mid-Autumn Festival holiday in China, Happy Mid-Autumn Festival !!!

**Comment by aleks-f** [comment]
> @aleks-f OK, Got it. Today is the first day of the Mid-Autumn Festival holiday in China, Happy Mid-Autumn Festival !!!

thank you! we have autumn starting here on September 23, technically it is still summer

**Comment by matejk** [comment]
> @siren186 if you care to do the windows, feel free to do so. see #4692

@siren186, @aleks-f: CMake for Linux, Windows and macOS was added.

**Pull request merged**
