### PR TITLE
Support for XDG Base Directory Specification

### PR DESCRIPTION
**Pull request by bschramke**
Made some little changes, that makes it easy to stick to [XDG Base Directory Specification][xdg].

On Linux its not a good idea to save configuration files beside the application's executable, because of executables normally located in '/usr/bin'. Also it's no good idea to clutter the users home directory with application specific data.

New methods:
* __Poco::Path::configHome()__ => Unix('~/.config/'), OSX('~/Library/Preferences/'), Win('%APPDATA%'), VxWorks & Other(invokes homeImpl)
* __Poco::Path::dataHome()__ => Unix('~/.local/share/'), OSX('~/Library/Application Support/'), Win('%LOCALAPPDATA%'), VxWorks & Other(invokes homeImpl)
* __Poco::Path::cacheHome()__ => Unix('~/.cache/'), OSX('~/Library/Caches/'), Win('%TEMP%'), VxWorks & Other(invokes tempImpl)
* __Poco::Path::tempHome()__ => Unix('~/.local/tmp/'), OSX('~/Library/Caches/'), Win('%TEMP%'), VxWorks & Other(invokes tempImpl)
* __Poco::Path::config()__ => Unix('/etc/'), OSX('/Library/Preferences/'), Win('%PROGRAMDATA%'), Other(invokes currentImpl)

New configuration values:

* __system.configHomeDir__ => Path::configHome()
* __system.cacheHomeDir__ => Path::cacheHome()
* __system.dataHomeDir__ => Path::dataHome()
* __system.tempHomeDir__ => Path::tempHome()
* __system.configDir__ => Path::config()

* __application.configDir__ => Path::configHome() + application.baseName
* __application.cacheDir__ => Path::cacheHome() + application.baseName
* __application.dataDir__ => Path::dataHome() + application.baseName
* __application.tempDir__ => Path::tempHome() + application.baseName

__EDIT:__ add OSX compliant implementation
__EDIT:__ add Windows compliant implementation

[xdg]: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html "XDG Base Directory Specification"

### CODE REVIEW

**Comment by aleks-f** [comment]
So @bschramke @obiltschnig @bakercp , is this good to be merged or does it require more work on various platforms?

**Comment by obiltschnig** [comment]
We should have meaningful Windows and OS X implementations before we merge this.

**Comment by bschramke** [comment]
I'm not sure if there are meaningful, but implementations for OSX and Windows are already there. I've tested the Linux and Windows implementations on openSUSE 13.1 and Windows 8, and they work fine. The mappings on Win and OSX maybe need some fine adjustment, especially the fallback mappings on Windows, but on the whole i think it's ready.

**Comment by aleks-f** [comment]
@obiltschnig any further comments or is it good to go?

**Comment by obiltschnig** [comment]
OK, looked at it again. Looks like everything's there already. The class documentation for SystemConfiguration should be updated to include the new properties.

**Comment by bschramke** [comment]
I've just updated the class documentation for SystemConfiguration and Application to reflect the new properties

**Comment by aleks-f** [comment]
Ok, great. This should go in 1.7.0; I'll fork off 1.6.1 and merge this into develop if there are no more objections.

**Pull request merged**
