### PR TITLE
Start POCO as Windows service with parameters fix

### PR DESCRIPTION
**Pull request by DomXC**
Fix of https://github.com/pocoproject/poco/issues/2190 is done using `static ArgVec _argsSvc; ` member, where args are passed to this member using `bool isService(const ArgVec& args); ` or `bool isService(int argc, wchar_t** argv);`.
Removed `int main(int argc, char** argv)` macro and `int ServerApplication::run(int argc, char** argv)` as it seems to be obsolete, because of wchar_t support only.

### CODE REVIEW

**Comment by DomXC** [comment]
Could someone, please, re-trigger the build, as I am confident, the fix does not break the consistency of the application? Thank you.

**Comment by aleks-f** [comment]
I restarted failed travis config, @zosrothko can you restart appveyor

**Comment by DomXC** [comment]
Thank you!

Anyway, any idea? I do not understand this:

 8/11 Test  #8: NetSSLWin ........................   Passed   61.73 sec
test 9
      Start  9: NetSSL
Could not find executable C:/projects/poco/cmake-build/bin/Debug/NetSSL-testrunner.exe
Looked in the following places:
C:/projects/poco/cmake-build/bin/Debug/NetSSL-testrunner.exe
C:/projects/poco/cmake-build/bin/Debug/NetSSL-testrunner.exe.exe
C:/projects/poco/cmake-build/bin/Debug/Debug/NetSSL-testrunner.exe
C:/projects/poco/cmake-build/bin/Debug/Debug/NetSSL-testrunner.exe.exe
Debug/C:/projects/poco/cmake-build/bin/Debug/NetSSL-testrunner.exe
Debug/C:/projects/poco/cmake-build/bin/Debug/NetSSL-testrunner.exe.exe
9: Test command:  "-all"
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to find executable: C:/projects/poco/cmake-build/bin/Debug/NetSSL-testrunner.exe
echo failure
failure
echo finish
finish

**Comment by aleks-f** [comment]
don't worry about that (or travis build for that matter), it can't be related to your changes, @zosrothko would know what's going on there

**Comment by georgi-g-ivanov** [comment]
Hello! We bumped into the same problem, which could be fixed by these changes. Is it planned to have this pull request merged and integrated into a release any time soon?

**Comment by DomXC** [comment]
I have been waiting for couple of months. Unfortunately, it seems like POCO is going to be a dead project...
But I don't want to spread any rumors, we could ask for comments @aleks-f.

**Comment by sujithsuranga** [comment]
Hello,
Could anyone kindly let me know if this issue has been resolved in the Poco library?

Thank you!

**Pull request closed without merging**
