### PR TITLE
PostgreSQL: integration with AppVeyor and Travis

### PR DESCRIPTION
**Pull request by zosrothko**
Hi

this PR brings integration of the Data/PostgreSQL module with the AppVeyor CI flow. The main issue to face on is the "postgres user' password setup which is different on AppVeyor from the traditional setup. AppVeyor sets the usr/pws as postgres/Password12! while on most of not all environment tests, usr/pwd is set to postgres/postgres. The second issue is to expurge all hard coded PostgreSQL paths from the VS project while keeping an easyway to debug the module. Here the changes

1/ The Data/PostgreSQL testunit suite sets the connection string using static methods that returns the host/port/database/user/password, the latest depending on the APPVEYOR environment variable.

2/ Building Data/PostgreSQL with msbuild requires to setup the LIB and INCLUDE variables as for MySQL

3/ Building Data/PostgreSQL within the VS IDE requires to add to the AppData\Local\Microsoft\MSBuild\v4.0\Microsoft.Cpp.x64.user.props with the PostgreSQL paths as for the LIB and INCLUDE variables as for example
	<PropertyGroup>
		<IncludePath>C:\Program Files\PostgreSQL\9.5\include;$(IncludePath)</IncludePath>
		<LibraryPath>C:\Program Files\PostgreSQL\9.5\lib;$(LibraryPath)</LibraryPath>
	</PropertyGroup>

4/ AppVeyor has been updated to the latest version of the develop branch as well as runtest2.cmd and runtests.sh

5/ Some module have been removed from the components file since there were failing at compilation on AppVeyor. This should be solved when the PostgreSQL branch will be merged with the develop branch.

6/ VS2013 Win32 projects have been added but the testsuite is run only for x64 for now. 

7/ Next steps are to run the Win32 testsuite on AppVeyor as well on Travis.

### CODE REVIEW

**Comment by zosrothko** [comment]
On Travis, the module Data/PostgreSQL compiles and its testsuite run but only for Linux OS as Postgres is not available for OSX. Below are the results for the Linux run. There are other errors in the Travis jobs but they are due to the branch PostgreSQL be far behind the develop branch.

****************************************
*** Linux x86_64 Data/PostgreSQL
****************************************

*** Connected to [PostgreSQL] test database.
Server Info: Process ID: 2295 Protocol Version: 3
Server Version: 90310
Host Info: localhost
Session Encoding: UTF8

testConnectNoDB: Attempting to Connect to [host=localhost user=postgres password=postgres] without database: 
Connected to [host=localhost user=postgres password=postgres] without database.
Server Info: Process ID: 2296 Protocol Version: 3
Server Version: 90310
Host Info: localhost
Session Encoding: UTF8
Disconnecting ...
Disconnected.

testPostgreSQLOIDs: Drop Table Test Result: PGRES_COMMAND_OK
Create Table Test Result: PGRES_COMMAND_OK

testSimpleAccess: 
testComplexType: 
testSimpleAccessVector: 
testComplexTypeVector: 
testInsertVector: 
testInsertEmptyVector: 
testInsertSingleBulk: 
testInsertSingleBulkVec: 
testLimit: 
testLimitOnce: 
testLimitPrepare: 
testLimitZero: 
testPrepare: 
testSetSimple: 
testSetComplex: 
testSetComplexUnique: 
testMultiSetSimple: 
testMultiSetComplex: 
testMapComplex: 
testMapComplexUnique: 
testMultiMapComplex: 
testSelectIntoSingle: 
testSelectIntoSingleStep: 
testSelectIntoSingleFail: 
testLowerLimitOk: 
testLowerLimitFail: 
testCombinedLimits: 
testCombinedIllegalLimits: 
testRange: 
testIllegalRange: 
testSingleSelect: 
testEmptyDB: 
testDateTime: 
lastname         firstname        address          birthday        
-------------------------------------------------------------------
Bart             Simpson          Springfield      1980-04-01T05:45:12Z

lastname         firstname        address          birthday        
-------------------------------------------------------------------
Bart             Simpson          Springfield      1980/04/01      

lastname         firstname        address          birthday        
-------------------------------------------------------------------
Bart             Simpson          Springfield      01:02:03        

testCLOBStmt: 
testBLOBStmt: 
testUnsignedInts: 
testFloat: 
testDouble: 
testTuple: 
testTupleVector: 
testInternalExtraction: 
testNull: 
testNullableInt: 
testNullableString: 
testTupleWithNullable: 
testSessionTransaction: Transaction isolation not supported: READ UNCOMMITTED

testTransaction: 
testReconnect: 

OK (50 tests)

**Comment by zosrothko** [comment]
Once the PostgreSQL branch merged with the develop branch, I will have to make some adjustments in the Makefile, in .travis.yml and in appveyor.yml.

**Comment by intensifi** [comment]
@zosrothko 
What specific issues are left in the PostgreSQL code base where I need to make changes?  I am unclear on what you have already updated and what else needs to be changed.

Also please note PostgreSQL is available on MacOSX.  I build and test with it there.

http://postgresapp.com

**Comment by zosrothko** [comment]
All changes are in the PR... but since the postgresql branch is far behing the develop branch, I copied and commited some stuff for making the Travis jobs working up to the end. Those debugging and WIP stuff will have to be fixed after the merge if any and I will take care of that.

PostgreSQL is availabel on OSX, fine, but it is not available on travis OSX... So even, if one can install it on travis, I would prefer to stabilize the CI AppVeyor for VS  and Travis for Linux before extending it on Travis  OSX.

**Comment by intensifi** [comment]
@zosrothko 

Thank you!

I'll review your PR in detail over the weekend.

**Pull request closed without merging**
