### PR TITLE
Add password field for Redis Client

### PR DESCRIPTION
**Pull request by kapcino**
@fbraem For issue #1824 I create a pull request for adding password field in Redis Client.
Please have a review, thanks.

### CODE REVIEW

**Comment by kapcino** [comment]
@fbraem You mean Iike this?

```
Poco::Redis::Client redis;
redis.connect(host, port);
redis.sendAuth(password);
```

It OK for single connection, but for the connection pool, it is not convenient as above.

```
Poco::Net::SocketAddress sa(_host, _port);
Poco::PoolableObjectFactory<Client, Client::Ptr> factory(sa);
Poco::ObjectPool<Client, Client::Ptr> pool(factory, 10, 15);
PooledConnection pclient1(pool);
```

If I want to add the password for the test code above, I need to add password into class PoolableObjectFactory, the current implement for createdObject() is:

```
Redis::Client::Ptr createObject()
{
    return new Redis::Client(_address);
}
```

Like the single connection, we should change like this:

```
Redis::Client::Ptr createObject()
{
    Redis::Client::Ptr ptr =  new Redis::Client(_address);
    ptr->sendAuth(_password);
    return ptr;
}
```

But it is not as simple as current one, so I change the constructor of Client and call sendAuth.

For the password problem, I will remove it from class.

**Comment by fbraem** [comment]
Maybe add a property to Client that indicates if sendAuth was called succesfully or not. That way we can check on a client that is returned from the pool if it is authenticated or not ...

**Comment by kapcino** [comment]
@fbraem Changed based on your comments, please review again, thanks!

**Comment by fbraem** [comment]
Sorry for my late answer, but I'm on a holiday for some weeks ...

Do we need the password in the pool class? Let the code that gets a client from the pool check if it is authenticated or not and call sendAuth if needed ... That way the password member is also not needed in the Pool class ...

**Comment by kapcino** [comment]
@fbraem Updated.

**Comment by fbraem** [comment]
This seems ok for me now. One question: is there a reason why you return true from sendAuth when the password is empty?

**Comment by kapcino** [comment]
@fbraem it is a bug, I've changed, thanks.

**Comment by fbraem** [comment]
@aleks-f : For me this enhancement is ok.
@kapcino : Thanks for your work.

**Pull request merged**
