### PR TITLE
fix : loop on sessionimpl->close

### PR DESCRIPTION
**Pull request by bas524**
if impl is sqlite and sqlite_close return SQLITE_BUSY

### CODE REVIEW

**Comment by bas524** [comment]
Hello! Guys what's a problem with builds, please look at that. I can't find any errors related with my commit.

**Comment by zosrothko** [comment]
it seems your changes are making the unit test in sqllite looping
```
****************************************
*** Linux x86_64 Data/SQLite
****************************************


testBinding: 
testZeroRows: 
testSimpleAccess: 
testInMemory: 
testNullCharPointer: 
testInsertCharPointer: 
testInsertCharPointer2: 
testComplexType: 
testSimpleAccessVector: 
testComplexTypeVector: 
testSharedPtrComplexTypeVector: 
testInsertVector: 
testInsertEmptyVector: 
testAffectedRows: 
testInsertSingleBulk: 
testInsertSingleBulkVec: 
testLimit: 
testLimitOnce: 
testLimitPrepare: 
testLimitZero: 
testPrepare: 
testSetSimple: 
testSetComplex: 
testSetComplexUnique: 
testMultiSetSimple: 
testMultiSetComplex: 
testMapComplex: 
testMapComplexUnique: 
testMultiMapComplex: 
testSelectIntoSingle: 
testSelectIntoSingleStep: 
testSelectIntoSingleFail: 
testLowerLimitOk: 
testLowerLimitFail: 
testCombinedLimits: 
testCombinedIllegalLimits: 
testRange: 
testIllegalRange: 
testSingleSelect: 
testEmptyDB: 
testCLOB: 
testTuple10: 
testTupleVector10: 
testTuple9: 
testTupleVector9: 
testTuple8: 
testTupleVector8: 
testTuple7: 
testTupleVector7: 
testTuple6: 
testTupleVector6: 
testTuple5: 
testTupleVector5: 
testTuple4: 
testTupleVector4: 
testTuple3: 
testTupleVector3: 
testTuple2: 
testTupleVector2: 
testTuple1: 
testTupleVector1: 
testDateTime: 
testInternalExtraction: 
testPrimaryKeyConstraint: 
testNullable: 
testNulls: 
testRowIterator: 
testAsync: 
testAny: 
testDynamicAny: 
testSQLChannel: 
testSQLLogger: 
testExternalBindingAndExtraction: 
testBindingCount: 
testMultipleResults: 
testPair: 
testReconnect: 
testThreadModes: Mode: single, Time: 616.955 [ms]
Mode: multi, Time: 643.802 [ms]
Mode: serial, Time: 567.689 [ms]

testUpdateCallback: Inserted main.Person, RowID=1
Updated main.Person, RowID=1
Deleted main.Person, RowID=1

testCommitCallback: 
testRollbackCallback: 
testNotifier: onInsert, row:1
onInsert, row:2
onInsert, row:3
onUpdate, row:1
onUpdate, row:2
onUpdate, row:3
onDelete, row:1
onDelete, row:2
onDelete, row:3
onCommit, row:0
onRollback, row:0



No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by aleks-f** [comment]
yes, I'm not keen on that potentially infinite loop in close. maybe try 10x and then let go. or, even better, figure out why exactly does close fail.

**Comment by bas524** [comment]
Ok, I'll try do it better

**Comment by aleks-f** [comment]
fixed with #1800

**Pull request closed without merging**
