### PR TITLE
Fixed compile error for OpenSSL 1.0 systems (#3739)

### PR DESCRIPTION
**Pull request by gyee-penguin**
Trying again -- not sure why it failed checks last time.

### CODE REVIEW

**Comment by aleks-f** [comment]
Pull requests should go to develop branch

**Comment by gyee-penguin** [comment]
Oops, my apologies.  I've changed the Pull Request to base off of devel.

**Comment by gyee-penguin** [comment]
Hello @aleks-f I don't think our patch is the reason for the checks failing.  I think the checks in the devel branch were failing before we committed.

**Comment by gyee-penguin** [comment]
Rebased with latest devel to see if that helps it pass checks

**Comment by gyee-penguin** [comment]
There seems to be a bug with the github checks.

**Comment by bas524** [comment]
Hi! I think, that problem a little bit more complicated than this PR. Please look at #3939

**Comment by gyee-penguin** [comment]
Hello!  Our patch does address the problem you mention.  We use a C macro to test the OpenSSL version and handle both cases (one where the function returns void and one that returns an int).

**Comment by gyee-penguin** [comment]
Hello @aleks-f Do you know if our patch is acceptable for the 1.12.5 release?

**Comment by bas524** [comment]
> Hello! Our patch does address the problem you mention. We use a C macro to test the OpenSSL version and handle both cases (one where the function returns void and one that returns an int).

Please, try build with openssl version 1.0.2. And you will see that in this version EVP_CIPHER_CTX returns void, and it will be a compile time error.
I have gotten it on solaris with openssl 1.0.2f

**Comment by gyee-penguin** [comment]
Hello @bas524, 

We successfully compiled against OpenSSL 1.0.2k on CentOS 7.  I agree that EVP_CIPHER_CTX_init returns void.  I can't explain why you are getting compile errors on your Solaris system, but below I explain why our patch works:

```
#if OPENSSL_VERSION_NUMBER >= 0x10100000L
	if (1 != EVP_CIPHER_CTX_init(_pCtx))
		handleErrors(std::string("Envelope():EVP_CIPHER_CTX_init()"));
#else
	EVP_CIPHER_CTX_init(_pCtx);
#endif
```

The first line ```#if OPENSSL_VERSION_NUMBER >= 0x10100000L``` tests if the OpenSSL version is >= 1.1.0.  If this is true, then we compile the version of EVP_CIPHER_CTX_init that returns an int.  

Otherwise, we compile the version that returns void.  This is true if OpenSSL version is 1.0.2, for example.

**Comment by bas524** [comment]
> Hello @bas524,
> 
> We successfully compiled against OpenSSL 1.0.2k on CentOS 7. I agree that EVP_CIPHER_CTX_init returns void. I can't explain why you are getting compile errors on your Solaris system, but below I explain why our patch works:
> 
> ```
> #if OPENSSL_VERSION_NUMBER >= 0x10100000L
> 	if (1 != EVP_CIPHER_CTX_init(_pCtx))
> 		handleErrors(std::string("Envelope():EVP_CIPHER_CTX_init()"));
> #else
> 	EVP_CIPHER_CTX_init(_pCtx);
> #endif
> ```
> 
> The first line `#if OPENSSL_VERSION_NUMBER >= 0x10100000L` tests if the OpenSSL version is >= 1.1.0. If this is true, then we compile the version of EVP_CIPHER_CTX_init that returns an int.
> 
> Otherwise, we compile the version that returns void. This is true if OpenSSL version is 1.0.2, for example.

I'm sorry. I was wrong. It was my inattention.
Your fix is correct. I have reused it for PR with fixes for solaris

**Pull request merged**
