### PR TITLE
NetEx library and SNMP

### PR DESCRIPTION
**Pull request by RangelReale**
* Created NetEx library and moved ICMP and NTP to it.
* Added SNMP to NetEx

Generated project files for vs100 (2010).

### CODE REVIEW

**Comment by aleks-f** [comment]
A travis build is failing, not sure why

**Comment by RangelReale** [comment]
There must be something wrong in the NetEx Makefile, I tested only using a static library, will try to compile shared to see if this is triggered.

** Compiling src/TCPServerConnectionFactory.cpp (debug, shared)
** Building shared library (debug) /home/travis/build/pocoproject/poco/lib/Linux/x86_64/libPocoNetExd.so.30
/usr/bin/ld: cannot find -lPocoNetd
collect2: ld returned 1 exit status
make[1]: *** [/home/travis/build/pocoproject/poco/lib/Linux/x86_64/libPocoNetExd.so.30] Error 1
make: *** [NetEx-libexec] Error 2

**Comment by RangelReale** [comment]
There is also my other PR #636 that add non-raw ICMP, can I also add it to this branch? As the ICMP files changed libraries, that PR would not work anymore.

**Comment by obiltschnig** [comment]
Given that we now have the NetEx library, I'd suggest moving the entire ICMP and NTP stuff there as well.

**Pull request merged**
