### PR TITLE
Don't try to install non existing Encodings/testsuite/data

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by jspricke** [comment]
@obiltschnig why do you close it? There is still no `Encodings/testsuite/data` directory, as far as I can see.

**Comment by obiltschnig** [comment]
Apparently GitHub closed it because I've renamed the develop branch

**Comment by jspricke** [comment]
should I send it for an other branch?

**Comment by obiltschnig** [comment]
Ideally against the poco-1.10.0 branch, then I can merge it directly into the upcoming release.

**Comment by obiltschnig** [comment]
Nevermind, merged it manually into poco-1.10.0.

**Comment by jspricke** [comment]
It was fixed in https://github.com/pocoproject/poco/commit/8329020858cb65e3d1f29926dda92cef5c885e25 for that branch (not in master btw.)

**Pull request closed without merging**
