### PR TITLE
Update HTTPSClientSession.h

### PR DESCRIPTION
**Pull request by MattPD**
Fix typo in the class documentation.

### CODE REVIEW

**Comment by MattPD** [comment]
One quick note: There were three files named `HTTPClientSession.h` affected by this (now two remaining) -- thus three patches: https://github.com/pocoproject/poco/search?utf8=%E2%9C%93&q=sendRequst

**Comment by aleks-f** [comment]
Sorry, in a rush I thought those were duplicates. They are merged now.

**Comment by MattPD** [comment]
No worries! Incidentally, I could use a workflow advice -- what's the recommended / best practice for deleting branches after PR (referring to GitHub's message "branch can be safely deleted")?

Delete or keep it around (I presume it depends on whether the "unknown repository" showing up as the origin is an issue or not: https://github.com/isaacs/github/issues/168)?

**Comment by aleks-f** [comment]
Expecting people to keep forever the pulled-from repository is not feasible; there's no way for us to control what people do. And it doesn't really matter IMO because all the relevant changes/commits are recorded in the pull.

**Comment by MattPD** [comment]
OK, thanks!

**Pull request merged**
