### PR TITLE
Revert "fix: android arm64/x86_64 compile error with getdtablesize"

### PR DESCRIPTION
**Pull request by obiltschnig**
Reverts pocoproject/poco#736

### CODE REVIEW

**Comment by obiltschnig** [comment]
Please resubmit pull request agains develop branch.

**Comment by aleks-f** [comment]
@obiltschnig : this revert went into a separate [branch](https://github.com/pocoproject/poco/tree/revert-736-master), master still has the original commit from the pull

**Comment by DanAlbert** [comment]
What was the compilation failure here? Reverting this makes poco incompatible with NDK r11.

**Comment by obiltschnig** [comment]
No compilation failure. We just don't like to merge pull requests into the master branch, because the master branch always matches the latest release. In the meantime, the fix is in 1.7.2, and so has again found its way into the master branch, although in the correct way.

**Pull request merged**
