### PR TITLE
Update for using g++ 5 & clang 3.5.0

### PR DESCRIPTION
**Pull request by zosrothko**
This PR make Travis CI building poco & running unit tests using g++ 5 and clang 3.5.0. Only Cmake jobs have been commented out due to a configuration issue.

### CODE REVIEW

**Comment by aleks-f** [comment]
@zosrothko do you plan to fix the cmake jobs as well? does this fix #1768 and makes #1769 obsolete?

**Comment by zosrothko** [comment]
@aleks-f I will fix CMake jobs and other running tests later on. This PR applies to the poco-c++11 branch and makes effective the Travis CI on c++11 usage in Poco. #1769 is different because it applies to the poco-develop branch which is not yet c++11 compliant. #1768 is the recommandation of Travis for removing the warning but it is ineffective since the warning is always on. Anyway, jobs are still running preperly until end. I will add the gcc 5 tests (bundled and unbundled) to the #1769.

**Comment by zosrothko** [comment]
@aleks-f The CMake jobs are working fine with g++ 5 but fails to use clang 3.5.0 and arm-linux-gnueabi-g++

Log for CMake with clang 3.5.0
```
7.32s$ mkdir cmake-build && cd cmake-build && cmake -DENABLE_TESTS=ON .. && make -s -j2 && ctest -VV -E Data && cd ..
-- The C compiler identification is Clang 3.5.0
-- The CXX compiler identification is Clang 3.5.0
[  0%] Building CXX object Foundation/CMakeFiles/Foundation.dir/src/MD4Engine.cpp.o
error: debug information for auto is not yet supported
error: debug information for auto is not yet supported
2 errors generated.
make[2]: *** [CppUnit/CMakeFiles/CppUnit.dir/src/TextTestResult.cpp.o] Error 1
make[1]: *** [CppUnit/CMakeFiles/CppUnit.dir/all] Error 2
```
Log for CMake witharm-linux-gnueabi-g++
```
cd cmake-build && cmake -DENABLE_NETSSL=OFF -DENABLE_CRYPTO=OFF -DENABLE_TESTS=ON .. && make -s -j2 && cd ..
-- The C compiler identification is GNU 4.7.3
-- The CXX compiler identification is GNU 4.7.3
```
I have no idea why the CMake clang/3.5.0 fails while make/clang 3.5.0 is fine. Moreover, the CMake/g++ 5 is working fine also.

CMake/arm-linux-gnueabi-g++ will never work because there is no arm-linux-gnueabi-g++ compiler compliant with c++11 on Ubuntu trusty.

Thus, you can merge this PR. The arm-linux-gnueabi-g++ will be restarted when the underlying platform will be Ubuntu zesty which have a arm-linux-gnueabi-g++compiler compliant with c++11.

**Comment by zosrothko** [comment]
Work reported in the updated c++11 branch of kampbell

**Pull request closed without merging**
