### PR TITLE
Complete Source IP address binding - combined

### PR DESCRIPTION
**Pull request by roccocorsi**
Fixes for:
- HTTPClientSession to support dual IPv4/IPv6 family when setting source IP address #2271
- HTTPClientSession not supporting binding source address for proxy connect #2270

### CODE REVIEW

**Comment by aleks-f** [comment]
travis is good, but net is segfaulting on windows, need to take a look, could be related to some recent changes in develop

**Comment by roccocorsi** [comment]
Failed again.  Is it something I changed or some other unrelated commit?

**Comment by roccocorsi** [comment]
@aleks-f Anything I should look at?  How do we see the backtrace for the coredump (I see segfault in the output).

**Comment by aleks-f** [comment]
heh, unfortunately, there is no code-supported backtrace for windows yet (I recently added g++, but that wont be of use here). essentially, you have to run Net test in debugger on windows and it will show the backtrace

**Comment by roccocorsi** [comment]
I've never had trouble compiling Poco (except if compiling SetSourceIP sample directly and needed C++11 cmake entry), but how to run the cppunit tests?  They don't appear to run for me.  What is the secret command?  :-)

**Comment by roccocorsi** [comment]
Sorry for such a beginner question.

**Comment by aleks-f** [comment]
depends on the platform/build system:
- makefiles: `$POCO_BASE/Net/testsuite$ bin/Linux/x86_[64]/testrunner -all`
- cmake: `$POCO_BASE/cmake-build-release/bin/Net-testruner -all`
- windows (VS): `%POCO_BASE%\Net\testsuite\bin[64]\TestSuite.exe -all`

**Comment by roccocorsi** [comment]
If I set POCO_BASE I can run test directly:
./NetSSL_OpenSSL/testsuite/bin/Linux/x86_64/testrunner -all

Is this the proper way?  How to run it with cmake or make??

**Comment by aleks-f** [comment]
> How to run it with cmake or make??

make, you just run it from command line directly. cmake, i use clion, but should also run from command line. `$POCO_BASE` is mainly used by make to build, but some tests rely on it to find some test runtime artifacts

**Comment by roccocorsi** [comment]
Just ran testrunner for NetSSL_OpenSSL under valgrind and it is reporting a few issues. Will look into them.

**Comment by roccocorsi** [comment]
I found a few faults in WebSocketTest.cpp with valgrind tool via NetSSL_OpenSSL testrunner, and I can see the same faults repeated in Net and NetSSL_Win.  Don't know for sure if they are the cause of the failures we are seeing with my jobs.  Will open another issue to fix it.

**Comment by aleks-f** [comment]
yes, I can reproduce. probably legit, they all point to Buffer

**Comment by roccocorsi** [comment]
Create issue

https://github.com/pocoproject/poco/issues/2323

and pull request

https://github.com/pocoproject/poco/pull/2324

**Comment by roccocorsi** [comment]
Still failing with the WebSocketTest.cpp fix, so problem is something else.

**Comment by aleks-f** [comment]
@roccocorsi please merge develop and let's see what happens with appveyor. the drmemory problems ("unaddressable access") were cleared with https://github.com/pocoproject/poco/commit/db9327e1da882b94fcf7afb08d2598a0506d4717

**Comment by roccocorsi** [comment]
@aleks-f Did you trigger the job?  I just rebased my branch with develop and push it to github.  Not sure if the currently running build job is testing something you updated or if it will run my latest changes.

**Comment by aleks-f** [comment]
it is queued automatically, will run when its turn comes.

**Comment by roccocorsi** [comment]
@aleks-f I pushed to my branch which is based on poco develop, but travis appears to be running tests on older commit.  I did a push force (git push -f origin ...) after I did rebase to top of develop.  Is this the problem?

**Comment by aleks-f** [comment]
no, it just depends of how many jobs are scheduled and travis seems to have a mind of its own. in any case, there is now android build problem, unrelated to this, appveyor passed so I'l merge it

**Pull request merged**
