### PR TITLE
Fix clang build error in poco 1.8.0

### PR DESCRIPTION
**Pull request by Bjoe**
Try to fix clang build error in poco 1.8.0 to get rid off to set libc++ for clang. See also issue #1973

### CODE REVIEW

**Comment by aleks-f** [comment]
@obiltschnig see #1973 
@Bjoe perhaps a cmake command-line switch would work better?

**Comment by Bjoe** [comment]
@aleks-f Hm I'm not sure what you mean exactly with command-line switch, but it is possible to set -DCMAKE_CXX_FLAGS="-stdlib=libc++", then poco is build with clang and C++14 via cmake. Should I add these in .travis.yml? At the moment, poco is build with clang and C++11 via cmake.

**Comment by aleks-f** [comment]
With my change clang will always compile with `-stdlib=libc++`. There should be a way to prevent that.

**Comment by Bjoe** [comment]
We can add an new cmake variable and verify if this variable is set via command parameter.
But I removed this line:
```
 set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} -stdlib=libc++")
```
because this will be make more problems then solve.

For example I get following error on my ubuntu without installing libc++:
```
20:54:54: Starte "/usr/bin/cmake" --build . --target all
[1/595 11.1/sec] Building CXX object Foundation/CMakeFiles/Foundation.dir/src/Base32Encoder.cpp.o
FAILED: Foundation/CMakeFiles/Foundation.dir/src/Base32Encoder.cpp.o 
/usr/bin/clang++-5.0   -DFoundation_EXPORTS -DHAVE_PTHREAD_SETAFFINITY_NP -DPCRE_STATIC -DPOCO_ENABLE_CPP11 -DPOCO_ENABLE_CPP14 -DPOCO_HAVE_FD_EPOLL -DPOCO_NO_AUTOMATIC_LIBS -DPOCO_OS_FAMILY_UNIX -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_REENTRANT -D_THREAD_SAFE -D_XOPEN_SOURCE=500 -I/poco/Foundation/include -I/poco/Foundation/src -stdlib=libc++ -g -D_DEBUG -fPIC   -std=gnu++14 -MD -MT Foundation/CMakeFiles/Foundation.dir/src/Base32Encoder.cpp.o -MF Foundation/CMakeFiles/Foundation.dir/src/Base32Encoder.cpp.o.d -o Foundation/CMakeFiles/Foundation.dir/src/Base32Encoder.cpp.o -c /poco/Foundation/src/Base32Encoder.cpp
In file included from /poco/Foundation/src/Base32Encoder.cpp:15:
In file included from /poco/Foundation/include/Poco/Base32Encoder.h:21:
In file included from /poco/Foundation/include/Poco/Foundation.h:113:
/poco/Foundation/include/Poco/Alignment.h:35:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
```
Nobody will understand that they have a missing libc++ library.
.libc++ is not the default standard C++ library on linux systems. Also not on android, but on android clang is the default compiler. We should use the "default" standard c++ lib" from the platform.

**Comment by aleks-f** [comment]
> We should use the "default" standard c++ lib" from the platform.

That's fine, just make sure travis builds ok.

I don't particularly like the solution proposed in this pull - trying to compile a hello world does not tell much. What I have done (and what has caused this issue with clang/libstdc++) is alignment with the [make](https://github.com/pocoproject/poco/blob/develop/build/script/cpp11-clang) determination of compiler c++11/14 capabilities, based on completeness of standard support (and which I now see should also be backported from develop to 1.8).

/cc @obiltschnig

**Comment by Bjoe** [comment]
> I don't particularly like the solution proposed in this pull - trying to compile a hello world does not tell much.
Ok. I try to compile against std::gets but this make no sense because it is removed in C++14 ...
Anyways I change my solution and set libc++ if it is possible and give a status message to install it. See my changes.
Hopefully this is more acceptable? Or any other ideas/comments?

But the best solution in my opinion is to use the cmake command **target_compile_features** See [compile-feature-requirements](https://cmake.org/cmake/help/v3.2/manual/cmake-compile-features.7.html#compile-feature-requirements)

**Comment by obiltschnig** [comment]
@bachp are you ok with the CMake changes here?

**Pull request merged**
