### PR TITLE
Usage modern C++ features on JSON modules

### PR DESCRIPTION
**Pull request by cngzhnp**
Starting from this module, I want to use modern C++ features such as:

- Use `nullptr` instead of 0.
- Use `auto` instead of iterator type itself.
- Use `default` keyword instead of copy constructor, destructor implementation
- Use `override` keyword if necessary.
- Use `using` keyword instead of `typedef`.
- Use proper functions like `empty()` call instead of `object.size() == 0`

### CODE REVIEW

**Comment by teksturi** [comment]
This is little bit old PR already but I still answer this. It does not make much sense to change style for just small portion of code base. It would be much better to do just one change at time. Example this

> * Use proper functions like `empty()` call instead of `object.size() == 0`

could be done to whole repo. It would be much more easy to accept those kind of changes.

**Comment by matejk** [comment]
#4354

**Comment by cngzhnp** [comment]
> This is little bit old PR already but I still answer this. It does not make much sense to change style for just small portion of code base. It would be much better to do just one change at time. Example this
> 
> > * Use proper functions like `empty()` call instead of `object.size() == 0`
> 
> could be done to whole repo. It would be much more easy to accept those kind of changes.

Hello @teksturi, sorry for late answer. 

However, my intention was not just a change into small portion of codebase like this, also I am not fan of inconsistent things. I just want to split up code review based on submodules. Creating a PR with 100 files changed which was not easy to review and apply changes. So, doing it step by step would be much better idea at least for me at that time.

**Comment by andrewauclair** [comment]
@matejk did you mean to delete devel? Doesn't seem right.

**Comment by matejk** [comment]
@cngzhnp, would you be willing to rebase this PR to main?

**Comment by matejk** [comment]
PR #4613 was created from these changes. See details there.

Closing this PR.

**Pull request closed without merging**
