### PR TITLE
POCO-1.7.6-all: Fixed Coverity CID 112767 Uninitialized pointer field…

### PR DESCRIPTION
**Pull request by SivaMaruti**
… (UNINIT_CTOR)

Fixed CID 112767 Uninitialized pointer field (UNINIT_CTOR) from
POCO-1.7.6.
Fixed uninit_member:Non-static class member _rptr, _fptr are not
initialized in this constructor nor in any functions that it calls

### CODE REVIEW

**Comment by SivaMaruti** [comment]
@obiltschnig:
Hi, Could you help merge these commits from https://github.com/pocoproject/poco/pull/1511

Thanks, Siva

**Comment by SivaMaruti** [comment]
@obiltschnig 

I've few commits related to coverity fixes done here https://github.com/pocoproject/poco/pull/1511 
Doing this first time and Need help here in approval merging these fixes.

Thanks,
Siva

**Comment by obiltschnig** [comment]
@SivaMaruti are you done with commits for now? I will then look at them and merge them.

**Comment by SivaMaruti** [comment]
@obiltschnig
Yes, I’m done with commits for now. You could take a look and merge them.
Regards,
-Siva

**Comment by SivaMaruti** [comment]
@obiltschnig
Could you look-in the commits #1511 and merge them.

**Comment by SivaMaruti** [comment]
@obiltschnig
I'm done with commits. 
1. Could you review the initial set of commits related to Coveriy CID fixes and merge them.
2. There's new commits pertaining to "warnings treated as errors" done today. The content is limited to warning fixes through #pragma disable, type casting and code restructuring.

Thanks,

**Comment by SivaMaruti** [comment]
@obiltschnig

**Comment by SivaMaruti** [comment]
@obiltschnig, What does "added this to the Release 1.8.0 milestone" implies? I'm assuming this to be considered for the Release 1.8.0. Pls confirm.

**Pull request closed without merging**
