### PR TITLE
Feat/openssl3 1.11.2

### PR DESCRIPTION
**Pull request by aleks-f**
OpenSSL 3 compile fixes

### CODE REVIEW

**Comment by aleks-f** [comment]
pending windows run

**Comment by aleks-f** [comment]
Windows test runs done. Both Windows and Linux proxy tests fail, I wasn't able to find a proxy that works (tried with wget, too). Also, apparently a clean shutdown is still an unreached goal (NetSSL both Linux and Windows):
```
testMultiConnections: EchoConnection: EchoConnection: SSL connection unexpectedly closed: error:0A000126:SSL routines::unexpected eof while readingSSL connection unexpectedly closed: error:0A000126:SSL routines::unexpected eof while reading
```
The test passes, though.

**Comment by obiltschnig** [comment]
Something does not look right in the PR. It adds/changes stuff that's already in poco-1.11.2.

**Comment by obiltschnig** [comment]
Something does not look right in the PR. It adds/changes stuff that's already in poco-1.11.2.

**Comment by obiltschnig** [comment]
PR needs to be cleaned up.

**Comment by obiltschnig** [comment]
This has a number of issues, most importantly, it seems to crash the testsuite. Also, not a clean patch, as it also introduces a new feature. Assigning to 1.12 for now - need to sort this out later.

**Comment by aleks-f** [comment]
@obiltschnig which tests crash? this is already merged in 1.12 branch and CI is green

**Comment by obiltschnig** [comment]
Don't remember which crashed. Left it out for now.

**Comment by obiltschnig** [comment]
Are you actually running the tests against OpenSSL 3?

**Comment by aleks-f** [comment]
yes, I was running on 3.0 and 1.1.1., plus there is now 3.0 in C and it's all green:https://github.com/pocoproject/poco/runs/6049589124?check_suite_focus=true

 Anyway, since this pull is already in the 1.12 release branch, I'll close it

**Pull request closed without merging**
