### PR TITLE
Add FTPS (FTP over explicit SSL) implementation

### PR DESCRIPTION
**Pull request by micheleselea**
Added FTPSClientSession to handle FTPS (FTP over Explicit SSL connection). I use this class from a couple of year without problem.
Basically FTPClientSession is like original, the only thing I changed are initialization order of variables to deal with gcc warning and put the request reading in a function.
FTPSClientSession extend FTPClientSession adding staff to do SSL connection over FTP

Status:

- [x] FTPS class implementation
- [x] Makefile
- [x] build vs140 32bit and 64bit
- [x] test vs140 64bit 
- [x] FTPSStreamFactory.cpp
- [x] OSX tests
- [x] build vs150
- [x] test vs150

### CODE REVIEW

**Comment by aleks-f** [comment]
Thanks @micheleselea , tests failing though on mac travis build; can you please take a look, or see with @zosrothko for any help to make them pass:

```
There were 12 errors: 
 1: N7CppUnit10TestCallerI21FTPSClientSessionTestEE.testLogin1
    "N4Poco3Net26ConnectionRefusedExceptionE: Connection refused"
    in "<unknown>", line -1
 2: N7CppUnit10TestCallerI21FTPSClientSessionTestEE.testLogin2
    "N4Poco3Net26ConnectionRefusedExceptionE: Connection refused"
    in "<unknown>", line -1
 3: N7CppUnit10TestCallerI21FTPSClientSessionTestEE.testLogin3
    "N4Poco3Net26ConnectionRefusedExceptionE: Connection refused"
    in "<unknown>", line -1
 4: N7CppUnit10TestCallerI21FTPSClientSessionTestEE.testLoginFailed1
    "N4Poco3Net26ConnectionRefusedExceptionE: Connection refused"
    in "<unknown>", line -1
 5: N7CppUnit10TestCallerI21FTPSClientSessionTestEE.testLoginFailed2
    "N4Poco3Net26ConnectionRefusedExceptionE: Connection refused"
    in "<unknown>", line -1
 6: N7CppUnit10TestCallerI21FTPSClientSessionTestEE.testCommands
    "N4Poco3Net26ConnectionRefusedExceptionE: Connection refused"
    in "<unknown>", line -1
 7: N7CppUnit10TestCallerI21FTPSClientSessionTestEE.testDownloadPORT
    "N4Poco3Net26ConnectionRefusedExceptionE: Connection refused"
    in "<unknown>", line -1
 8: N7CppUnit10TestCallerI21FTPSClientSessionTestEE.testDownloadEPRT
    "N4Poco3Net26ConnectionRefusedExceptionE: Connection refused"
    in "<unknown>", line -1
 9: N7CppUnit10TestCallerI21FTPSClientSessionTestEE.testDownloadPASV
    "N4Poco3Net26ConnectionRefusedExceptionE: Connection refused"
    in "<unknown>", line -1
10: N7CppUnit10TestCallerI21FTPSClientSessionTestEE.testDownloadEPSV
    "N4Poco3Net26ConnectionRefusedExceptionE: Connection refused"
    in "<unknown>", line -1
11: N7CppUnit10TestCallerI21FTPSClientSessionTestEE.testUpload
    "N4Poco3Net26ConnectionRefusedExceptionE: Connection refused"
    in "<unknown>", line -1
12: N7CppUnit10TestCallerI21FTPSClientSessionTestEE.testList
    "N4Poco3Net26ConnectionRefusedExceptionE: Connection refused"
    in "<unknown>", line -1
```

**Comment by aleks-f** [comment]
also, no need to worry about VS < 2015, 2.0 will not support anything older than 2015

**Comment by micheleselea** [comment]
@aleks-f yes I'm going to fix it, I don't understand why, it give the same strange issue to me with "localhost" changed to "127.0.0.1" it works for me...but I can't understand...anyway I'll try if travis works with 127.0.0.1 than I'll dig it

**Comment by zosrothko** [comment]
@micheleselea "I don't understand why, it give the same strange issue to me with "localhost" changed to "127.0.0.1" it works for me...but I can't understand". This is an issue with DNS and ipv4/ipv6 resolution. Look into closed Poco issues, you will find out the point.

**Comment by micheleselea** [comment]
@zosrothko @aleks-f so with 127.0.0.1 works and with localhost gives "Connection refused" very strange, should be the same...can't understand. The strange thing is that if you try connecting with a StreamSocket result in the same...I have to dig it...

**Comment by micheleselea** [comment]
the very strange thing is that you should have the same error with FTPClientSession test suite....has the same tests I used code from there.....

**Comment by micheleselea** [comment]
@aleks-f @zosrothko 
The strange thing is that in the original FTP client test the code is like
`FTPClientSession session("127.0.0.1", server.port());`
so something was already changed and we do not use anymore localhost
but things getting darker: if you have a look to the latest poco lib release you will found
`FTPClientSession session("localhost", server.port());`
So it seams something changed in "localhost" parsing? because "localhost" is given to FTPClientSession that in the end give it to a SocketAddress used to construct a DialogSocket, the problem could be if something changed in SocketAddress parsing. I'm going to check it and let you know

**Comment by micheleselea** [comment]
This piece of code
```
Poco::Net::SocketAddress sa1;
Poco::Net::ServerSocket serv;
serv.bind(sa1);
serv.listen();
Poco::Net::StreamSocket ss;
Poco::Timespan timeout(250000);
Poco::Net::SocketAddress sa2("localhost", serv.address().port());
ss.connect(sa2, timeout);

```
works with poco 1.7.8p3 and not with the develop branch, probably something in SocketAddress changed...digging...

**Comment by micheleselea** [comment]
Ok I probably found the difference between 1.7.8p3 and develop
In function `void SocketAddress::init(const std::string& hostAddress, Poco::UInt16 portNumber)`
```
{
#if defined(POCO_HAVE_IPv6) && !defined(POCO_SOCKETADDRESS_DONT_PREFER_IPV4)
	// if we get both IPv4 and IPv6 addresses, prefer IPv4
	std::stable_sort(addresses.begin(), addresses.end(), AFLT());
#endif
	init(addresses[0], portNumber);
}
```
doing the function `std::stable_sort(addresses.begin(), addresses.end(), AFLT());` or not change the behavior between the 2 lib version

**Comment by micheleselea** [comment]
```
Poco::Net::SocketAddress sa1;
Poco::Net::ServerSocket serv;
serv.bind(sa1);
serv.listen();
Poco::Net::StreamSocket ss;
Poco::Timespan timeout(250000);
Poco::Net::SocketAddress sa2("localhost", serv.address().port());
ss.connect(sa2, timeout);
```
changing from `Poco::Net::SocketAddress sa1;` to `Poco::Net::SocketAddress sa1("localhost",0);` solve the issue, but probablì che main problem is the default SocketAddress() constructor that should act as we use ("localhost",0)

**Comment by aleks-f** [comment]
yes, it should default to IPv4
/cc @obiltschnig

**Comment by aleks-f** [comment]
IPv4/v6 preference was changed [here](https://github.com/pocoproject/poco/commit/6195c97a868b7f61f5ad993f5a90eccb6a3df339#diff-2ce271e0dc976c018a34a8166b332a03L253), but I'm not sure why

**Comment by micheleselea** [comment]
@aleks-f Compilation is fine now, do you need the vs150 build and test? I can upload it

**Comment by aleks-f** [comment]
Sure, push it here and I'll merge

**Comment by micheleselea** [comment]
I think you should check the sln file because I'll do it with vs2015 not with 2017. Should be the same but in the header I see the Visual Studio 14 instead Visual Studio 2017

**Comment by aleks-f** [comment]
@zosrothko that's something to discuss with @obiltschnig , he did the change and I'm not sure of what the rationale for it was - best to create another issue, discuss and keep track of eventual changes there

**Comment by obiltschnig** [comment]
Moved to 1.10 due to time constraints.

**Pull request merged**
