### PR TITLE
Update FindMySQL.cmake

### PR DESCRIPTION
**Pull request by FalseCAM**
Find MYSQL_LIB by names mysqlclient and mysqlclient_r.

### CODE REVIEW

**Comment by FalseCAM** [comment]
Ubuntu 16.04 has no mysqlclient_r but mysqlclient.

**Comment by bachp** [comment]
+1

**Comment by zosrothko** [comment]
The AppVeyor fails with
C:\projects\poco\MongoDB\include\Poco/MongoDB/PoolableConnectionFactory.h(111) : error C2610: Poco::MongoDB::PooledConnection::PooledConnection(Poco::MongoDB::PooledConnection &&)' : is not a special member function which can be defaulted
C:\projects\poco\MongoDB\include\Poco/MongoDB/PoolableConnectionFactory.h(112) : error C2610: 'Poco::MongoDB::PooledConnection &Poco::MongoDB::PooledConnection::operator =(Poco::MongoDB::PooledConnection &&)' : is not a special member function which can be defaulted
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~3.0\VC\bin\cl.exe' : return code '0x2'
Stop.

Someone should take care of this error...

**Comment by aleks-f** [comment]
@zosrothko : why is it failing here and not in dev?

**Comment by zosrothko** [comment]
Apparently with the latest develop branch of PoolableConnectionFactory.h, CMake is building with POCO_ENABLE_CPP11 set, which is wrong in case of AppVeyor builds

#if defined(POCO_ENABLE_CPP11)
	// Disable copy to prevent unwanted release of resources: C++11 way
    PooledConnection(const PooledConnection&) = delete;
    PooledConnection& operator=(const PooledConnection&) = delete;

    // Enable move semantics
    PooledConnection(PooledConnection&& other) = default;
    PooledConnection& operator=(PooledConnection&&) = default;
#endif

private:
#if ! defined(POCO_ENABLE_CPP11)
	// Disable copy to prevent unwanted release of resources: pre C++11 way
    PooledConnection(const PooledConnection&);
    PooledConnection& operator=(const PooledConnection&);
#endif

**Pull request merged**
