### PR TITLE
Reset connection when a session is returned to the SessionPool

### PR DESCRIPTION
**Pull request by Erbengi**
Fix of issue #2546

### CODE REVIEW

**Comment by Erbengi** [comment]
Ok, I've renamed the methods.

**Comment by Erbengi** [comment]
It seems that function `mysql_reset_connection()` was added in MySQL 5.7, but CI machines use 5.6. Probably `mysql_refresh()` should be a solution but I need to test it first.

**Comment by Erbengi** [comment]
`mysql_refresh()` seems working same as `mysql_reset_connection()`

**Comment by obiltschnig** [comment]
Ideally, since `mysql_refresh()` is marked as deprecated, you should check for the MySQL client version and switch between `mysql_refresh()` and `mysql_reset_connection()` using the preprocessor.

**Pull request merged**
