### PR TITLE
Virtualize ServerApplication::handlePidFile()

### PR DESCRIPTION
**Pull request by pavledragisic**

### CODE REVIEW

**Comment by obiltschnig** [comment]
Why doesn't `replaceOption()` take an `Option` parameter, like `addOption()`? Seems inconsistent.

**Comment by aleks-f** [comment]
> Why doesn't `replaceOption()` take an `Option` parameter, like `addOption()`? Seems inconsistent.

@pavledragisic change it, but it also requires changes on our side (devs, dispatcher and s7server) so either align it on our side or create an issue there

**Comment by obiltschnig** [comment]
Then at least also add an `addOption()` overload, please, so that the API stays consistent.

**Comment by aleks-f** [comment]
> Then at least also add an `addOption()` overload, please, so that the API stays consistent.

alright, @pavledragisic do it like that

**Comment by aleks-f** [comment]
@obiltschnig after a bit more thinking, how about this instead:
```c++
template <typename T>
void OptionSet::replaceHandler(const std::string& opt, T* pObj, Callback<T> func)
```

That is really what we need - to tell the `Application` that we will handle this option and replacing the whole Option is the proverbial cannon to kill a mosquito :)

**Comment by aleks-f** [comment]
> If that's all you need, then how about just making `handlePidFile()`, `handleDaemon()`, etc. virtual?

virtualizing will work; at this time, I would limit it to handlePidFile only and I would also like to move it out of #ifdef FAMILY_UNIX, so that it is available on all platforms

**Comment by aleks-f** [comment]
> > If that's all you need, then how about just making `handlePidFile()`, `handleDaemon()`, etc. virtual?
> 
> virtualizing will work; at this time, I would limit it to handlePidFile only and I would also like to move it out of #ifdef FAMILY_UNIX, so that it is available on all platforms

@pavledragisic do it like this ^
https://github.com/pocoproject/poco/blob/e47b92d641d3efffe9a81cf8f4a940f7267a015b/Util/include/Poco/Util/ServerApplication.h#L174
discard current changes in this branch, move this function out of #ifdef, and make it virtual. We then have to override it in our processes that require strict PID creation timing

**Pull request merged**
