### PR TITLE
Fixed issue #705 Error building with ENABLE_UTIL=ON and ENABLE_XML=OFF

### PR DESCRIPTION
**Pull request by Gamadril**
Updated Util/CMakeLists.txt to link against JSON and XML libraries only if necessary

### CODE REVIEW

**Comment by bachp** [comment]
Thanks. 
Looks good.

@aleks-f Please merge
I don't know if #821 is needed as-well?

**Comment by aleks-f** [comment]
See [#821](https://github.com/pocoproject/poco/pull/821)

**Comment by bachp** [comment]
Shouldn't this change go to develop too?

**Comment by aleks-f** [comment]
Looks same like [#821](https://github.com/pocoproject/poco/pull/821). Am I missing something?

**Comment by Gamadril** [comment]
This one is for the develop branch. #821 was for poco-1.6.1 branch. Since it is the current official stable one I thought it would be a good idea to update both...

**Comment by aleks-f** [comment]
Ah that's what happens when working from phone - it doesn't show to which branch pull goes. Anyway, can't merge it from phone now, Travis is failing so it won't let me.

**Pull request merged**
