### PR TITLE
Gradle for Poco 1.8.0

### PR DESCRIPTION
**Pull request by zosrothko**
Hi

This PR is a backport of the Gradle's build files found in the feature-gradle branch. When poco-1.8.0 will be ready for release, this gradle build will produce automatically a NuGet package and a Windows MSI packaging for VisualStudio 2015 by invoking the command: `build\gradle\bin\gradle packaging`

None of the poco-1.8.0 c++ file have been changed except the Environment class and the PocoDoc directory.

### CODE REVIEW

**Comment by aleks-f** [comment]
@obiltschnig this is [Apache](https://github.com/pocoproject/poco/pull/1957/commits/619838a45f42a62985fc60358c8444eae2e683af#diff-3baddbe0bf6b3cfedd0ae520c10957a0) licensed. OK to merge?

**Comment by obiltschnig** [comment]
Uh, can we keep that whole Gradle .jar stuff outside of the Poco main repository please? In a separate repository perhaps, then imported as submodule? And is it really necessary that we manage/ship the complete Gradle build system? We also don't ship the CMake binaries and support files.

**Comment by obiltschnig** [comment]
I guess the Apache license refers to Gradle itself, not the scripts and config files to build Poco with Gradle?

**Comment by aleks-f** [comment]
@zosrothko I'm with @obiltschnig on this - scripts can remain but anything apache licensed should go to [gradle](https://github.com/pocoproject/gradle) repo and we can include it in poco repo as git module (but not ship it in release packages). we do the same with openssl

**Comment by zosrothko** [comment]
Ok, will put the gradle.jars in a submodule... One needs a specific Gradle version stored in pocoproject/gradle repo because there are Poco plugins built in like the Windows Message Compiler plugin and the CppUnitTest plugin. The Apache licence applies to Gradle itself, not to the scripts themself.

**Pull request closed without merging**
