### PR TITLE
Add setaffinity method to thread implementation and interface class

### PR DESCRIPTION
**Pull request by bas524**
Limit specified thread to run only on the specified core.

### CODE REVIEW

**Comment by aleks-f** [comment]
Thanks, can you do few more things before merge:
- add getAffinity()
- add testcase
- throw Poco::NotImplementedException instead of silently doing nothing for platforms where not implemented

**Comment by bas524** [comment]
Thread affinity support for *nix, windows and mac os x 
Sorry for the indentation

**Comment by bas524** [comment]
Sorry for the indentation

**Comment by aleks-f** [comment]
could you please fix the indentation before I merge it? I know it may seem like a minor issue but when you have to deal with a few merges every day, it becomes quite a task to keep everything in order.
thanks

**Comment by bas524** [comment]
Have you got config file for astyle, or something like astyle. ? 


Отправлено с устройства Samsung

-------- Исходное сообщение --------
От: Aleksandar Fabijanic <notifications@github.com> 
Дата: 2015.03.07  21:19  (GMT+03:00) 
Кому: pocoproject/poco <poco@noreply.github.com> 
Копия: Alexander B <bas524@ya.ru> 
Тема: Re: [poco] Add setaffinity method to thread implementation and
  interface class (#730) 

could you please fix the indentation before I merge it? I know it may seem like a minor issue but when you have to deal with a few merges every day, it becomes quite a task to keep everything in order.

thanks

**Comment by aleks-f** [comment]
Unfortunately, no. We have [Style Guide](http://www.appinf.com/download/CppCodingStyleGuide.pdf) but it has not been formalized into a tool/configuration. We would not mind a contribution based on, say [LibFormat](http://clang.llvm.org/docs/LibFormat.html).

**Comment by bas524** [comment]
merge it please, and i create a config for clang-format.

**Pull request merged**
