### PR TITLE
Fix Visual Studio warnings at level /W4

### PR DESCRIPTION
**Pull request by mkrivos**

### CODE REVIEW

**Comment by mkrivos** [comment]
More fixes coming soon ...

**Comment by mkrivos** [comment]
Done, except SQL ODBC (because of corrupted VS solution).

**Comment by mkrivos** [comment]
ODBC_x64_vs150.sln  and vs 2017 reports corrupted file

**Comment by aleks-f** [comment]
@mkrivos here you go:
```diff
λ git diff SQL\ODBC\ODBC_x64_vs150.sln                                                                                         
diff --git a/SQL/ODBC/ODBC_x64_vs150.sln b/SQL/ODBC/ODBC_x64_vs150.sln                                                         
index cb6a5aee9..d5eb4186e 100644                                                                                              
--- a/SQL/ODBC/ODBC_x64_vs150.sln                                                                                              
+++ b/SQL/ODBC/ODBC_x64_vs150.sln                                                                                              
@@ -1,4 +1,4 @@                                                                                                                
-SQL Visual Studio Solution File, Format Version 12.00                                                                         
+Microsoft Visual Studio Solution File, Format Version 12.00                                                                   
 # Visual Studio 2017                                                                                                          
 Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "ODBC", "ODBC_x64_vs150.vcxproj", "{1B29820D-375F-11DB-837B-00123FC423B5}"
 EndProject                                                                                                                    
```

**Pull request merged**
