### PR TITLE
Change Foundation library version back to SHARED_LIBRARY_VERSION

### PR DESCRIPTION
**Pull request by mikedld**
Foundation is the only library using PROJECT_VERSION as library version, the change accidentally introduced by commit b69fafb84c. This causes difference in library being linked to (libPocoFoundation.31.dylib on Mac) and library returned by `$<TARGET_FILE:Poco::Foundation>` for imported target (libPocoFoundation.1.6.1.dylib), causing inconvenience. Also, this differs from autoconf-based builds where only "31" (soversion) library is being created and not "1.6.1" (project version) one.

This closes issue #944.

### CODE REVIEW

**Comment by mikedld** [comment]
Just wondering, will this change make it into 1.6.2? If not, what's the next stable version number it'll be in, 1.6.3 or 1.7?

**Comment by bachp** [comment]
I would say this should be included in 1.6.2, as it fixes an obvious error.
@obiltschnig What you think? 1.6.2 is not out as far as I know?

**Comment by obiltschnig** [comment]
I'm okay with that. Could you merge/cherry-pick the changes into the 1.6.2 branch?

**Comment by bachp** [comment]
@obiltschnig I don't have commit access. Could you do that?

**Pull request merged**
