### PR TITLE
Clang and GCC version detection for C++11/14

### PR DESCRIPTION
**Pull request by RangelReale**
Also sync to develop

### CODE REVIEW

**Comment by aleks-f** [comment]
Few minor things:
1) beware that changes to VS project files will be overwritten every time [progen](https://github.com/pocoproject/poco/tree/develop/ProGen) is used to regenerate them
2) although not recommended, likely or common, in theory gcc and g++ can be of different versions - it is best to use g++ because that's what matters here
3) a nitpick related to 2 - let's call those variables GXX* instead of GCC*

**Comment by RangelReale** [comment]
For my changes I only changed the Makefiles, if there are any VS project file changes, thay must have come from the merge from develop.

**Comment by RangelReale** [comment]
Changed to use g++ instead of gcc

**Comment by aleks-f** [comment]
Apparently, travis is using g++ 4.6 and something is leaking. Maybe add `-std=c++0x` for lower versions of g++ that support it?
```
** Compiling src/FIFOBufferStream.cpp (debug, shared)
In file included from /usr/include/c++/4.6/type_traits:35:0,
                 from include/Poco/Format.h:26,
                 from include/Poco/FIFOBuffer.h:28,
                 from include/Poco/FIFOBufferStream.h:24,
                 from src/FIFOBufferStream.cpp:17:
/usr/include/c++/4.6/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.
```

**Comment by RangelReale** [comment]
Done.

**Comment by aleks-f** [comment]
looks like some travis builds are still failing, not sure why. maybe @zosrothko would know

**Comment by zosrothko** [comment]
Some builds are failing because of c++0x
In file included from /usr/include/c++/4.6/type_traits:35:0,

                 from include/Poco/Format.h:26,

                 from include/Poco/FIFOBuffer.h:28,

                 from include/Poco/FIFOBufferStream.h:24,

                 from src/FIFOBufferStream.cpp:17:

/usr/include/c++/4.6/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.

Some build are failing because they repo is using cmake3

Ask people to update their development branch versus pocoproject/poco@develop

**Comment by aleks-f** [comment]
@zosrothko : but in this specific pull case, `-std=c++0x was added and linux make build is still failing

**Comment by RangelReale** [comment]
Ok, the problem is because of the 

#include <type_traits>

which should be protected with CPP11 define.

**Comment by zosrothko** [comment]
Also the makedependcy.gcc does not preprend with -std=c++11 which popups the error

** Creating dependency info for src/Var.cpp

/usr/include/c++/4.6/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.

**Comment by RangelReale** [comment]
This last travis error is strange, it is using clang (3.4), but looks like it is including header files from gcc?

    $ clang --version
    clang version 3.4 (tags/RELEASE_34/final)
    Target: x86_64-unknown-linux-gnu

    In file included from /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/type_traits:35:
    /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/bits/c++0x_warning.h:32:2: error: 
          This file requires compiler and
          library support for the upcoming
          ISO C++ standard, C++0x. This
          support is currently experimental,
          and must be enabled with the
          -std=c++0x or -std=gnu++0x
          compiler options.

**Comment by aleks-f** [comment]
probably libstdc++

**Comment by RangelReale** [comment]
Creating a better pull request for this, closing for now

**Pull request closed without merging**
