### PR TITLE
Foundation: fix memory leaks in Logger sample

### PR DESCRIPTION
**Pull request by vmiklos**
At least valgrind now doesn't point out leaks anymore.

### CODE REVIEW

**Comment by vmiklos** [comment]
Hi,

Can I help you anything to get this merged?

Thanks,

Miklos

**Comment by vmiklos** [comment]
Hi,

Ping again? :-)

Thanks,

Miklos

**Comment by fbraem** [comment]
I think it's better to use Poco::AutoPtr

**Comment by vmiklos** [comment]
I've updated the commit to use Poco::AutoPtr.

**Pull request merged**
