### PR TITLE
fix(CppUint) : RepeatedTest compile error

### PR DESCRIPTION
**Pull request by HR1025**

### CODE REVIEW

**Comment by HR1025** [comment]
https://github.com/pocoproject/poco/pull/3757
Is it modified like this???

**Comment by aleks-f** [comment]
I don't know, I can't make sense of it - the previous pull is gone, and there's no `RepeatedTest.cpp` in this one. In any case, if you want that cpp file added, the it will have to be added to the `CppUnit` Makefile and all VS projects.

**Comment by HR1025** [comment]
i think the RepeatedTest.cpp is little redundant, so remove it , but include the header and delete forward declare

**Comment by HR1025** [comment]
previous pull disappear may be i use the git push -f to update my commit

**Pull request merged**
